// Package tinkuclient contains generated service clients.
//
// Code generated by csilgen; DO NOT EDIT.
package tinkuclient

import (
	"context"
	"fmt"
)

// ClientError is returned by a generated client call: a structured error the
// service returned (Code/Message), or a transport-level failure (Err).
type ClientError struct {
	Code    int64
	Message string
	Err     error
}

func (e *ClientError) Error() string {
	if e.Err != nil {
		return "transport error: " + e.Err.Error()
	}
	return fmt.Sprintf("service error %d: %s", e.Code, e.Message)
}

// Transport is the caller-supplied byte carrier: it performs the call named by
// (service, op) with the already-encoded request bytes and returns the response
// bytes, or an error. Both names are the verbatim CSIL names (service as written,
// op in kebab-case as written), ready to go on the wire unmodified. The generated
// client owns (de)serialization via the codec; the carrier only moves bytes, so
// it can be HTTP, a queue, or an in-process loop.
type Transport interface {
	Call(ctx context.Context, service string, op string, req []byte) ([]byte, error)
}

// AuthClient is a typed client for the AuthService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type AuthClient struct {
	transport Transport
}

func NewAuthClient(transport Transport) *AuthClient {
	return &AuthClient{transport: transport}
}

func (c *AuthClient) BeginLogin(ctx context.Context, req BeginLoginRequest) (BeginLoginResponse, error) {
	var csilZero BeginLoginResponse
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "begin-login", EncodeBeginLoginRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeBeginLoginResponse(csilResp)
}

func (c *AuthClient) Logout(ctx context.Context, req Empty) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "logout", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *AuthClient) Whoami(ctx context.Context, req Empty) (UserProfile, error) {
	var csilZero UserProfile
	csilResp, csilErr := c.transport.Call(ctx, "AuthService", "whoami", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUserProfile(csilResp)
}

// DevAuthClient is a typed client for the DevAuthService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type DevAuthClient struct {
	transport Transport
}

func NewDevAuthClient(transport Transport) *DevAuthClient {
	return &DevAuthClient{transport: transport}
}

func (c *DevAuthClient) DevLogin(ctx context.Context, req DevLoginRequest) (UserProfile, error) {
	var csilZero UserProfile
	csilResp, csilErr := c.transport.Call(ctx, "DevAuthService", "dev-login", EncodeDevLoginRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUserProfile(csilResp)
}

// GreetingClient is a typed client for the GreetingService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type GreetingClient struct {
	transport Transport
}

func NewGreetingClient(transport Transport) *GreetingClient {
	return &GreetingClient{transport: transport}
}

func (c *GreetingClient) ListGreetings(ctx context.Context, req Empty) (GreetingList, error) {
	var csilZero GreetingList
	csilResp, csilErr := c.transport.Call(ctx, "GreetingService", "list-greetings", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGreetingList(csilResp)
}

func (c *GreetingClient) GetGreeting(ctx context.Context, req GetGreetingRequest) (Greeting, error) {
	var csilZero Greeting
	csilResp, csilErr := c.transport.Call(ctx, "GreetingService", "get-greeting", EncodeGetGreetingRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGreeting(csilResp)
}

func (c *GreetingClient) CreateGreeting(ctx context.Context, req CreateGreetingRequest) (Greeting, error) {
	var csilZero Greeting
	csilResp, csilErr := c.transport.Call(ctx, "GreetingService", "create-greeting", EncodeCreateGreetingRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGreeting(csilResp)
}

// OrganizationClient is a typed client for the OrganizationService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type OrganizationClient struct {
	transport Transport
}

func NewOrganizationClient(transport Transport) *OrganizationClient {
	return &OrganizationClient{transport: transport}
}

func (c *OrganizationClient) ListOrganizations(ctx context.Context, req ListOrganizationsRequest) (OrganizationList, error) {
	var csilZero OrganizationList
	csilResp, csilErr := c.transport.Call(ctx, "OrganizationService", "list-organizations", EncodeListOrganizationsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeOrganizationList(csilResp)
}

func (c *OrganizationClient) GetOrganization(ctx context.Context, req GetOrganizationRequest) (Organization, error) {
	var csilZero Organization
	csilResp, csilErr := c.transport.Call(ctx, "OrganizationService", "get-organization", EncodeGetOrganizationRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeOrganization(csilResp)
}

func (c *OrganizationClient) CreateOrganization(ctx context.Context, req CreateOrganizationRequest) (Organization, error) {
	var csilZero Organization
	csilResp, csilErr := c.transport.Call(ctx, "OrganizationService", "create-organization", EncodeCreateOrganizationRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeOrganization(csilResp)
}

func (c *OrganizationClient) UpdateOrganization(ctx context.Context, req UpdateOrganizationRequest) (Organization, error) {
	var csilZero Organization
	csilResp, csilErr := c.transport.Call(ctx, "OrganizationService", "update-organization", EncodeUpdateOrganizationRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeOrganization(csilResp)
}

func (c *OrganizationClient) DeleteOrganization(ctx context.Context, req DeleteOrganizationRequest) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "OrganizationService", "delete-organization", EncodeDeleteOrganizationRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *OrganizationClient) ListOrganizationMembers(ctx context.Context, req ListOrganizationMembersRequest) (OrganizationMemberList, error) {
	var csilZero OrganizationMemberList
	csilResp, csilErr := c.transport.Call(ctx, "OrganizationService", "list-organization-members", EncodeListOrganizationMembersRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeOrganizationMemberList(csilResp)
}

func (c *OrganizationClient) SetOrganizationMember(ctx context.Context, req SetOrganizationMemberRequest) (OrganizationMemberList, error) {
	var csilZero OrganizationMemberList
	csilResp, csilErr := c.transport.Call(ctx, "OrganizationService", "set-organization-member", EncodeSetOrganizationMemberRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeOrganizationMemberList(csilResp)
}

func (c *OrganizationClient) RemoveOrganizationMember(ctx context.Context, req RemoveOrganizationMemberRequest) (OrganizationMemberList, error) {
	var csilZero OrganizationMemberList
	csilResp, csilErr := c.transport.Call(ctx, "OrganizationService", "remove-organization-member", EncodeRemoveOrganizationMemberRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeOrganizationMemberList(csilResp)
}

// GatheringClient is a typed client for the GatheringService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type GatheringClient struct {
	transport Transport
}

func NewGatheringClient(transport Transport) *GatheringClient {
	return &GatheringClient{transport: transport}
}

func (c *GatheringClient) ListGatherings(ctx context.Context, req ListGatheringsRequest) (GatheringList, error) {
	var csilZero GatheringList
	csilResp, csilErr := c.transport.Call(ctx, "GatheringService", "list-gatherings", EncodeListGatheringsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGatheringList(csilResp)
}

func (c *GatheringClient) GetGathering(ctx context.Context, req GetGatheringRequest) (Gathering, error) {
	var csilZero Gathering
	csilResp, csilErr := c.transport.Call(ctx, "GatheringService", "get-gathering", EncodeGetGatheringRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGathering(csilResp)
}

func (c *GatheringClient) CreateGathering(ctx context.Context, req CreateGatheringRequest) (Gathering, error) {
	var csilZero Gathering
	csilResp, csilErr := c.transport.Call(ctx, "GatheringService", "create-gathering", EncodeCreateGatheringRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGathering(csilResp)
}

func (c *GatheringClient) UpdateGathering(ctx context.Context, req UpdateGatheringRequest) (Gathering, error) {
	var csilZero Gathering
	csilResp, csilErr := c.transport.Call(ctx, "GatheringService", "update-gathering", EncodeUpdateGatheringRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGathering(csilResp)
}

func (c *GatheringClient) DeleteGathering(ctx context.Context, req DeleteGatheringRequest) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "GatheringService", "delete-gathering", EncodeDeleteGatheringRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *GatheringClient) ListGatheringMembers(ctx context.Context, req ListGatheringMembersRequest) (GatheringMemberList, error) {
	var csilZero GatheringMemberList
	csilResp, csilErr := c.transport.Call(ctx, "GatheringService", "list-gathering-members", EncodeListGatheringMembersRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGatheringMemberList(csilResp)
}

func (c *GatheringClient) JoinGathering(ctx context.Context, req JoinGatheringRequest) (Gathering, error) {
	var csilZero Gathering
	csilResp, csilErr := c.transport.Call(ctx, "GatheringService", "join-gathering", EncodeJoinGatheringRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGathering(csilResp)
}

func (c *GatheringClient) LeaveGathering(ctx context.Context, req LeaveGatheringRequest) (Gathering, error) {
	var csilZero Gathering
	csilResp, csilErr := c.transport.Call(ctx, "GatheringService", "leave-gathering", EncodeLeaveGatheringRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGathering(csilResp)
}

func (c *GatheringClient) AddGatheringOwner(ctx context.Context, req AddGatheringOwnerRequest) (Gathering, error) {
	var csilZero Gathering
	csilResp, csilErr := c.transport.Call(ctx, "GatheringService", "add-gathering-owner", EncodeAddGatheringOwnerRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGathering(csilResp)
}

func (c *GatheringClient) RemoveGatheringOwner(ctx context.Context, req RemoveGatheringOwnerRequest) (Gathering, error) {
	var csilZero Gathering
	csilResp, csilErr := c.transport.Call(ctx, "GatheringService", "remove-gathering-owner", EncodeRemoveGatheringOwnerRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGathering(csilResp)
}

// EventClient is a typed client for the EventService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type EventClient struct {
	transport Transport
}

func NewEventClient(transport Transport) *EventClient {
	return &EventClient{transport: transport}
}

func (c *EventClient) ListEvents(ctx context.Context, req ListEventsRequest) (EventList, error) {
	var csilZero EventList
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "list-events", EncodeListEventsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEventList(csilResp)
}

func (c *EventClient) GetEvent(ctx context.Context, req GetEventRequest) (Event, error) {
	var csilZero Event
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "get-event", EncodeGetEventRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEvent(csilResp)
}

func (c *EventClient) CreateEvent(ctx context.Context, req CreateEventRequest) (Event, error) {
	var csilZero Event
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "create-event", EncodeCreateEventRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEvent(csilResp)
}

func (c *EventClient) UpdateEvent(ctx context.Context, req UpdateEventRequest) (Event, error) {
	var csilZero Event
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "update-event", EncodeUpdateEventRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEvent(csilResp)
}

func (c *EventClient) DeleteEvent(ctx context.Context, req DeleteEventRequest) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "delete-event", EncodeDeleteEventRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *EventClient) AttendEvent(ctx context.Context, req AttendEventRequest) (Event, error) {
	var csilZero Event
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "attend-event", EncodeAttendEventRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEvent(csilResp)
}

func (c *EventClient) UnattendEvent(ctx context.Context, req UnattendEventRequest) (Event, error) {
	var csilZero Event
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "unattend-event", EncodeUnattendEventRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEvent(csilResp)
}

func (c *EventClient) ListAttendees(ctx context.Context, req ListAttendeesRequest) (AttendeeList, error) {
	var csilZero AttendeeList
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "list-attendees", EncodeListAttendeesRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeAttendeeList(csilResp)
}

func (c *EventClient) ListEventSeries(ctx context.Context, req ListEventSeriesRequest) (EventSeriesList, error) {
	var csilZero EventSeriesList
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "list-event-series", EncodeListEventSeriesRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEventSeriesList(csilResp)
}

func (c *EventClient) GetEventSeries(ctx context.Context, req GetEventSeriesRequest) (EventSeries, error) {
	var csilZero EventSeries
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "get-event-series", EncodeGetEventSeriesRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEventSeries(csilResp)
}

func (c *EventClient) CreateEventSeries(ctx context.Context, req CreateEventSeriesRequest) (EventSeries, error) {
	var csilZero EventSeries
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "create-event-series", EncodeCreateEventSeriesRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEventSeries(csilResp)
}

func (c *EventClient) UpdateEventSeries(ctx context.Context, req UpdateEventSeriesRequest) (EventSeries, error) {
	var csilZero EventSeries
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "update-event-series", EncodeUpdateEventSeriesRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEventSeries(csilResp)
}

func (c *EventClient) DeleteEventSeries(ctx context.Context, req DeleteEventSeriesRequest) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "delete-event-series", EncodeDeleteEventSeriesRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *EventClient) ExpandEventSeries(ctx context.Context, req ExpandEventSeriesRequest) (EventList, error) {
	var csilZero EventList
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "expand-event-series", EncodeExpandEventSeriesRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEventList(csilResp)
}

func (c *EventClient) SetEventRole(ctx context.Context, req SetEventRoleRequest) (EventRoleList, error) {
	var csilZero EventRoleList
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "set-event-role", EncodeSetEventRoleRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEventRoleList(csilResp)
}

func (c *EventClient) RemoveEventRole(ctx context.Context, req RemoveEventRoleRequest) (EventRoleList, error) {
	var csilZero EventRoleList
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "remove-event-role", EncodeRemoveEventRoleRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEventRoleList(csilResp)
}

func (c *EventClient) ListEventRoles(ctx context.Context, req ListEventRolesRequest) (EventRoleList, error) {
	var csilZero EventRoleList
	csilResp, csilErr := c.transport.Call(ctx, "EventService", "list-event-roles", EncodeListEventRolesRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEventRoleList(csilResp)
}

// SearchClient is a typed client for the SearchService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type SearchClient struct {
	transport Transport
}

func NewSearchClient(transport Transport) *SearchClient {
	return &SearchClient{transport: transport}
}

func (c *SearchClient) Search(ctx context.Context, req SearchRequest) (SearchResults, error) {
	var csilZero SearchResults
	csilResp, csilErr := c.transport.Call(ctx, "SearchService", "search", EncodeSearchRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeSearchResults(csilResp)
}

// AdminClient is a typed client for the AdminService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type AdminClient struct {
	transport Transport
}

func NewAdminClient(transport Transport) *AdminClient {
	return &AdminClient{transport: transport}
}

func (c *AdminClient) ListAdmins(ctx context.Context, req Empty) (AdminList, error) {
	var csilZero AdminList
	csilResp, csilErr := c.transport.Call(ctx, "AdminService", "list-admins", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeAdminList(csilResp)
}

func (c *AdminClient) SetAdmin(ctx context.Context, req SetAdminRequest) (AdminList, error) {
	var csilZero AdminList
	csilResp, csilErr := c.transport.Call(ctx, "AdminService", "set-admin", EncodeSetAdminRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeAdminList(csilResp)
}

func (c *AdminClient) FindUser(ctx context.Context, req FindUserRequest) (UserRef, error) {
	var csilZero UserRef
	csilResp, csilErr := c.transport.Call(ctx, "AdminService", "find-user", EncodeFindUserRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUserRef(csilResp)
}

func (c *AdminClient) SearchUsers(ctx context.Context, req SearchUsersRequest) (UserRefList, error) {
	var csilZero UserRefList
	csilResp, csilErr := c.transport.Call(ctx, "AdminService", "search-users", EncodeSearchUsersRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUserRefList(csilResp)
}

func (c *AdminClient) GetInstanceSettings(ctx context.Context, req Empty) (InstanceSettings, error) {
	var csilZero InstanceSettings
	csilResp, csilErr := c.transport.Call(ctx, "AdminService", "get-instance-settings", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeInstanceSettings(csilResp)
}

func (c *AdminClient) UpdateInstanceSettings(ctx context.Context, req UpdateInstanceSettingsRequest) (InstanceSettings, error) {
	var csilZero InstanceSettings
	csilResp, csilErr := c.transport.Call(ctx, "AdminService", "update-instance-settings", EncodeUpdateInstanceSettingsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeInstanceSettings(csilResp)
}

// FederationClient is a typed client for the FederationService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type FederationClient struct {
	transport Transport
}

func NewFederationClient(transport Transport) *FederationClient {
	return &FederationClient{transport: transport}
}

func (c *FederationClient) FederationIdentity(ctx context.Context, req Empty) (FederationIdentity, error) {
	var csilZero FederationIdentity
	csilResp, csilErr := c.transport.Call(ctx, "FederationService", "federation-identity", EncodeEmpty(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeFederationIdentity(csilResp)
}

func (c *FederationClient) ListPeers(ctx context.Context, req ListPeersRequest) (PeerList, error) {
	var csilZero PeerList
	csilResp, csilErr := c.transport.Call(ctx, "FederationService", "list-peers", EncodeListPeersRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodePeerList(csilResp)
}

func (c *FederationClient) AddPeer(ctx context.Context, req AddPeerRequest) (Peer, error) {
	var csilZero Peer
	csilResp, csilErr := c.transport.Call(ctx, "FederationService", "add-peer", EncodeAddPeerRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodePeer(csilResp)
}

func (c *FederationClient) SetPeerStatus(ctx context.Context, req SetPeerStatusRequest) (Peer, error) {
	var csilZero Peer
	csilResp, csilErr := c.transport.Call(ctx, "FederationService", "set-peer-status", EncodeSetPeerStatusRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodePeer(csilResp)
}

func (c *FederationClient) ResumePeer(ctx context.Context, req ResumePeerRequest) (Peer, error) {
	var csilZero Peer
	csilResp, csilErr := c.transport.Call(ctx, "FederationService", "resume-peer", EncodeResumePeerRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodePeer(csilResp)
}

func (c *FederationClient) RemovePeer(ctx context.Context, req RemovePeerRequest) (Empty, error) {
	var csilZero Empty
	csilResp, csilErr := c.transport.Call(ctx, "FederationService", "remove-peer", EncodeRemovePeerRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeEmpty(csilResp)
}

func (c *FederationClient) DeliverEvents(ctx context.Context, req SignedDelivery) (DeliveryReceipt, error) {
	var csilZero DeliveryReceipt
	csilResp, csilErr := c.transport.Call(ctx, "FederationService", "deliver-events", EncodeSignedDelivery(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeDeliveryReceipt(csilResp)
}

func (c *FederationClient) RequestPeering(ctx context.Context, req SignedPeeringRequest) (PeeringReceipt, error) {
	var csilZero PeeringReceipt
	csilResp, csilErr := c.transport.Call(ctx, "FederationService", "request-peering", EncodeSignedPeeringRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodePeeringReceipt(csilResp)
}

func (c *FederationClient) ListRemoteEvents(ctx context.Context, req ListRemoteEventsRequest) (RemoteEventList, error) {
	var csilZero RemoteEventList
	csilResp, csilErr := c.transport.Call(ctx, "FederationService", "list-remote-events", EncodeListRemoteEventsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRemoteEventList(csilResp)
}

func (c *FederationClient) SetPeerRateLimit(ctx context.Context, req SetPeerRateLimitRequest) (Peer, error) {
	var csilZero Peer
	csilResp, csilErr := c.transport.Call(ctx, "FederationService", "set-peer-rate-limit", EncodeSetPeerRateLimitRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodePeer(csilResp)
}

func (c *FederationClient) ListOriginVolume(ctx context.Context, req ListOriginVolumeRequest) (OriginVolumeList, error) {
	var csilZero OriginVolumeList
	csilResp, csilErr := c.transport.Call(ctx, "FederationService", "list-origin-volume", EncodeListOriginVolumeRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeOriginVolumeList(csilResp)
}

func (c *FederationClient) SetOriginRateLimit(ctx context.Context, req SetOriginRateLimitRequest) (OriginVolume, error) {
	var csilZero OriginVolume
	csilResp, csilErr := c.transport.Call(ctx, "FederationService", "set-origin-rate-limit", EncodeSetOriginRateLimitRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeOriginVolume(csilResp)
}
