// Package tinkuclient contains generated service interfaces.
//
// Code generated by csilgen; DO NOT EDIT.
package tinkuclient

import (
	"context"
)

// AuthService defines the service interface
type AuthService interface {
	BeginLogin(ctx context.Context, req BeginLoginRequest) (BeginLoginResponse, error)
	Logout(ctx context.Context, req Empty) (Empty, error)
	Whoami(ctx context.Context, req Empty) (UserProfile, error)
}

// Wire-id ordinals for the AuthService service (transport compact profiles).
const AuthServiceServiceWireID uint64 = 1
const AuthServiceOpBeginLoginWireID uint64 = 0
const AuthServiceOpLogoutWireID uint64 = 1
const AuthServiceOpWhoamiWireID uint64 = 2

// DevAuthService defines the service interface
type DevAuthService interface {
	DevLogin(ctx context.Context, req DevLoginRequest) (UserProfile, error)
}

// Wire-id ordinals for the DevAuthService service (transport compact profiles).
const DevAuthServiceServiceWireID uint64 = 2
const DevAuthServiceOpDevLoginWireID uint64 = 0

// GreetingService defines the service interface
type GreetingService interface {
	ListGreetings(ctx context.Context, req Empty) (GreetingList, error)
	GetGreeting(ctx context.Context, req GetGreetingRequest) (Greeting, error)
	CreateGreeting(ctx context.Context, req CreateGreetingRequest) (Greeting, error)
}

// Wire-id ordinals for the GreetingService service (transport compact profiles).
const GreetingServiceServiceWireID uint64 = 3
const GreetingServiceOpListGreetingsWireID uint64 = 0
const GreetingServiceOpGetGreetingWireID uint64 = 1
const GreetingServiceOpCreateGreetingWireID uint64 = 2

// OrganizationService defines the service interface
type OrganizationService interface {
	ListOrganizations(ctx context.Context, req ListOrganizationsRequest) (OrganizationList, error)
	GetOrganization(ctx context.Context, req GetOrganizationRequest) (Organization, error)
	CreateOrganization(ctx context.Context, req CreateOrganizationRequest) (Organization, error)
	UpdateOrganization(ctx context.Context, req UpdateOrganizationRequest) (Organization, error)
	DeleteOrganization(ctx context.Context, req DeleteOrganizationRequest) (Empty, error)
	ListOrganizationMembers(ctx context.Context, req ListOrganizationMembersRequest) (OrganizationMemberList, error)
	SetOrganizationMember(ctx context.Context, req SetOrganizationMemberRequest) (OrganizationMemberList, error)
	RemoveOrganizationMember(ctx context.Context, req RemoveOrganizationMemberRequest) (OrganizationMemberList, error)
}

// Wire-id ordinals for the OrganizationService service (transport compact profiles).
const OrganizationServiceServiceWireID uint64 = 4
const OrganizationServiceOpListOrganizationsWireID uint64 = 0
const OrganizationServiceOpGetOrganizationWireID uint64 = 1
const OrganizationServiceOpCreateOrganizationWireID uint64 = 2
const OrganizationServiceOpUpdateOrganizationWireID uint64 = 3
const OrganizationServiceOpDeleteOrganizationWireID uint64 = 4
const OrganizationServiceOpListOrganizationMembersWireID uint64 = 5
const OrganizationServiceOpSetOrganizationMemberWireID uint64 = 6
const OrganizationServiceOpRemoveOrganizationMemberWireID uint64 = 7

// GatheringService defines the service interface
type GatheringService interface {
	ListGatherings(ctx context.Context, req ListGatheringsRequest) (GatheringList, error)
	GetGathering(ctx context.Context, req GetGatheringRequest) (Gathering, error)
	CreateGathering(ctx context.Context, req CreateGatheringRequest) (Gathering, error)
	UpdateGathering(ctx context.Context, req UpdateGatheringRequest) (Gathering, error)
	DeleteGathering(ctx context.Context, req DeleteGatheringRequest) (Empty, error)
	ListGatheringMembers(ctx context.Context, req ListGatheringMembersRequest) (GatheringMemberList, error)
	JoinGathering(ctx context.Context, req JoinGatheringRequest) (Gathering, error)
	LeaveGathering(ctx context.Context, req LeaveGatheringRequest) (Gathering, error)
	AddGatheringOwner(ctx context.Context, req AddGatheringOwnerRequest) (Gathering, error)
	RemoveGatheringOwner(ctx context.Context, req RemoveGatheringOwnerRequest) (Gathering, error)
	OfferGathering(ctx context.Context, req OfferGatheringRequest) (GatheringOffer, error)
	ListGatheringOffers(ctx context.Context, req ListGatheringOffersRequest) (GatheringOfferList, error)
	RespondToGatheringOffer(ctx context.Context, req RespondToGatheringOfferRequest) (GatheringOffer, error)
	WithdrawGatheringOffer(ctx context.Context, req WithdrawGatheringOfferRequest) (Empty, error)
	AdoptGathering(ctx context.Context, req AdoptGatheringRequest) (Gathering, error)
}

// Wire-id ordinals for the GatheringService service (transport compact profiles).
const GatheringServiceServiceWireID uint64 = 5
const GatheringServiceOpListGatheringsWireID uint64 = 0
const GatheringServiceOpGetGatheringWireID uint64 = 1
const GatheringServiceOpCreateGatheringWireID uint64 = 2
const GatheringServiceOpUpdateGatheringWireID uint64 = 3
const GatheringServiceOpDeleteGatheringWireID uint64 = 4
const GatheringServiceOpListGatheringMembersWireID uint64 = 5
const GatheringServiceOpJoinGatheringWireID uint64 = 6
const GatheringServiceOpLeaveGatheringWireID uint64 = 7
const GatheringServiceOpAddGatheringOwnerWireID uint64 = 8
const GatheringServiceOpRemoveGatheringOwnerWireID uint64 = 9
const GatheringServiceOpOfferGatheringWireID uint64 = 10
const GatheringServiceOpListGatheringOffersWireID uint64 = 11
const GatheringServiceOpRespondToGatheringOfferWireID uint64 = 12
const GatheringServiceOpWithdrawGatheringOfferWireID uint64 = 13
const GatheringServiceOpAdoptGatheringWireID uint64 = 14

// EventService defines the service interface
type EventService interface {
	ListEvents(ctx context.Context, req ListEventsRequest) (EventList, error)
	GetEvent(ctx context.Context, req GetEventRequest) (Event, error)
	CreateEvent(ctx context.Context, req CreateEventRequest) (Event, error)
	UpdateEvent(ctx context.Context, req UpdateEventRequest) (Event, error)
	DeleteEvent(ctx context.Context, req DeleteEventRequest) (Empty, error)
	AttendEvent(ctx context.Context, req AttendEventRequest) (Event, error)
	UnattendEvent(ctx context.Context, req UnattendEventRequest) (Event, error)
	ListAttendees(ctx context.Context, req ListAttendeesRequest) (AttendeeList, error)
	ListEventSeries(ctx context.Context, req ListEventSeriesRequest) (EventSeriesList, error)
	GetEventSeries(ctx context.Context, req GetEventSeriesRequest) (EventSeries, error)
	CreateEventSeries(ctx context.Context, req CreateEventSeriesRequest) (EventSeries, error)
	UpdateEventSeries(ctx context.Context, req UpdateEventSeriesRequest) (EventSeries, error)
	DeleteEventSeries(ctx context.Context, req DeleteEventSeriesRequest) (Empty, error)
	ExpandEventSeries(ctx context.Context, req ExpandEventSeriesRequest) (EventList, error)
	SetEventRole(ctx context.Context, req SetEventRoleRequest) (EventRoleList, error)
	RemoveEventRole(ctx context.Context, req RemoveEventRoleRequest) (EventRoleList, error)
	ListEventRoles(ctx context.Context, req ListEventRolesRequest) (EventRoleList, error)
}

// Wire-id ordinals for the EventService service (transport compact profiles).
const EventServiceServiceWireID uint64 = 6
const EventServiceOpListEventsWireID uint64 = 0
const EventServiceOpGetEventWireID uint64 = 1
const EventServiceOpCreateEventWireID uint64 = 2
const EventServiceOpUpdateEventWireID uint64 = 3
const EventServiceOpDeleteEventWireID uint64 = 4
const EventServiceOpAttendEventWireID uint64 = 5
const EventServiceOpUnattendEventWireID uint64 = 6
const EventServiceOpListAttendeesWireID uint64 = 7
const EventServiceOpListEventSeriesWireID uint64 = 8
const EventServiceOpGetEventSeriesWireID uint64 = 9
const EventServiceOpCreateEventSeriesWireID uint64 = 10
const EventServiceOpUpdateEventSeriesWireID uint64 = 11
const EventServiceOpDeleteEventSeriesWireID uint64 = 12
const EventServiceOpExpandEventSeriesWireID uint64 = 13
const EventServiceOpSetEventRoleWireID uint64 = 14
const EventServiceOpRemoveEventRoleWireID uint64 = 15
const EventServiceOpListEventRolesWireID uint64 = 16

// SearchService defines the service interface
type SearchService interface {
	Search(ctx context.Context, req SearchRequest) (SearchResults, error)
}

// Wire-id ordinals for the SearchService service (transport compact profiles).
const SearchServiceServiceWireID uint64 = 7
const SearchServiceOpSearchWireID uint64 = 0

// AdminService defines the service interface
type AdminService interface {
	ListAdmins(ctx context.Context, req Empty) (AdminList, error)
	SetAdmin(ctx context.Context, req SetAdminRequest) (AdminList, error)
	FindUser(ctx context.Context, req FindUserRequest) (UserRef, error)
	SearchUsers(ctx context.Context, req SearchUsersRequest) (UserRefList, error)
	GetInstanceSettings(ctx context.Context, req Empty) (InstanceSettings, error)
	UpdateInstanceSettings(ctx context.Context, req UpdateInstanceSettingsRequest) (InstanceSettings, error)
}

// Wire-id ordinals for the AdminService service (transport compact profiles).
const AdminServiceServiceWireID uint64 = 8
const AdminServiceOpListAdminsWireID uint64 = 0
const AdminServiceOpSetAdminWireID uint64 = 1
const AdminServiceOpFindUserWireID uint64 = 2
const AdminServiceOpSearchUsersWireID uint64 = 3
const AdminServiceOpGetInstanceSettingsWireID uint64 = 4
const AdminServiceOpUpdateInstanceSettingsWireID uint64 = 5

// FederationService defines the service interface
type FederationService interface {
	FederationIdentity(ctx context.Context, req Empty) (FederationIdentity, error)
	ListPeers(ctx context.Context, req ListPeersRequest) (PeerList, error)
	AddPeer(ctx context.Context, req AddPeerRequest) (Peer, error)
	SetPeerStatus(ctx context.Context, req SetPeerStatusRequest) (Peer, error)
	ResumePeer(ctx context.Context, req ResumePeerRequest) (Peer, error)
	RemovePeer(ctx context.Context, req RemovePeerRequest) (Empty, error)
	DeliverEvents(ctx context.Context, req SignedDelivery) (DeliveryReceipt, error)
	RequestPeering(ctx context.Context, req SignedPeeringRequest) (PeeringReceipt, error)
	ListRemoteEvents(ctx context.Context, req ListRemoteEventsRequest) (RemoteEventList, error)
	SetPeerRateLimit(ctx context.Context, req SetPeerRateLimitRequest) (Peer, error)
	ListOriginVolume(ctx context.Context, req ListOriginVolumeRequest) (OriginVolumeList, error)
	SetOriginRateLimit(ctx context.Context, req SetOriginRateLimitRequest) (OriginVolume, error)
}

// Wire-id ordinals for the FederationService service (transport compact profiles).
const FederationServiceServiceWireID uint64 = 9
const FederationServiceOpFederationIdentityWireID uint64 = 0
const FederationServiceOpListPeersWireID uint64 = 1
const FederationServiceOpAddPeerWireID uint64 = 2
const FederationServiceOpSetPeerStatusWireID uint64 = 3
const FederationServiceOpResumePeerWireID uint64 = 4
const FederationServiceOpRemovePeerWireID uint64 = 5
const FederationServiceOpDeliverEventsWireID uint64 = 6
const FederationServiceOpRequestPeeringWireID uint64 = 7
const FederationServiceOpListRemoteEventsWireID uint64 = 8
const FederationServiceOpSetPeerRateLimitWireID uint64 = 9
const FederationServiceOpListOriginVolumeWireID uint64 = 10
const FederationServiceOpSetOriginRateLimitWireID uint64 = 11

// WebhookService defines the service interface
type WebhookService interface {
	ListWebhooks(ctx context.Context, req ListWebhooksRequest) (WebhookList, error)
	CreateWebhook(ctx context.Context, req CreateWebhookRequest) (WebhookWithSecret, error)
	UpdateWebhook(ctx context.Context, req UpdateWebhookRequest) (Webhook, error)
	DeleteWebhook(ctx context.Context, req DeleteWebhookRequest) (Empty, error)
}

// Wire-id ordinals for the WebhookService service (transport compact profiles).
const WebhookServiceServiceWireID uint64 = 10
const WebhookServiceOpListWebhooksWireID uint64 = 0
const WebhookServiceOpCreateWebhookWireID uint64 = 1
const WebhookServiceOpUpdateWebhookWireID uint64 = 2
const WebhookServiceOpDeleteWebhookWireID uint64 = 3
