// Code generated by csilgen. DO NOT EDIT.
// Source: <csil spec>
// Target: typescript-typesonly

/**
 * A user's id (ULID).
 */
export type UserID = string;

/**
 * A greeting's id (ULID).
 */
export type GreetingID = string;

/**
 * An organization's id (ULID).
 */
export type OrganizationID = string;

/**
 * A gathering's id (ULID).
 */
export type GatheringID = string;

/**
 * An event's id (ULID). Every occurrence of a series has one of these,
 * because an occurrence IS an event.
 */
export type EventID = string;

/**
 * An event series' id (ULID).
 */
export type EventSeriesID = string;

/**
 * A webhook's id (ULID).
 */
export type WebhookID = string;

/**
 * An offer's id (ULID). One gathering offered to one organization.
 */
export type GatheringOfferID = string;

/**
 * The empty payload. Ops that take no input and ops that return nothing
 * both use it, so every op still has a declared request and response type.
 */
export interface Empty {
}

/**
 * What the calling session may do with the resource carried alongside this
 * block. The server resolves the whole permission model once and reports
 * the answer, so a client never re-implements it — a client that decides
 * for itself drifts from the server the first time a rule changes, and the
 * server is the only side that can be trusted anyway.
 * 
 * Flags a given resource cannot have are always false: an organization
 * has no organizers, so `is_organizer` is false on every organization.
 */
export interface ViewerContext {
  /**
   * The caller holds the global admin role.
   */
  isAdmin: boolean;
  /**
   * The caller owns this resource, directly or through an organization
   * that owns it.
   */
  isOwner: boolean;
  /**
   * The caller is an organizer of this event or series, or of its parent
   * series.
   */
  isOrganizer: boolean;
  /**
   * The caller is a presenter. Presenters carry no permission beyond a
   * member's; the flag exists so the UI can show the billing.
   */
  isPresenter: boolean;
  /**
   * The caller has a member's ACCESS. Owners and organizers do, whether
   * or not they ever joined, because every power a member has they have
   * too. Read this to decide what somebody may DO.
   */
  isMember: boolean;
  /**
   * The caller is on the roster: they joined, and leaving would remove a
   * row. This is NOT is_member — an owner has a member's access without
   * having joined anything. Read this to decide what a Join or Leave
   * control should say, or it will offer "Leave" to somebody who never
   * joined and can never make it change.
   */
  hasJoined: boolean;
  /**
   * The caller may change this resource's own fields.
   */
  canEdit: boolean;
  /**
   * The caller may destroy this resource. Deleting an organization, or
   * an event that has already started, is reserved to admins.
   */
  canDelete: boolean;
  /**
   * The caller may add and remove this resource's members and roles.
   */
  canManageMembers: boolean;
}

/**
 * How far into a list to read. Every list and search op takes one so that
 * no op can be made to return an unbounded result set; the server clamps
 * `limit` to its own maximum regardless of what is asked for.
 */
export interface Page {
  /**
   * How many rows to return. Defaults to 25 when zero, capped at 100.
   */
  limit?: number;
  /**
   * How many rows to skip. Offset paging, not cursor paging: this is a
   * prototype, and an offset is the honest shape for one. A real
   * deployment wants a cursor before the first table gets large.
   */
  offset?: number;
}

/**
 * Whether a thing's events are published to the directories this instance
 * peers with.
 * 
 * `unset` is a THIRD state, not a synonym for `out`: it means this level
 * has said nothing and the level above decides. A boolean could not carry
 * it, which is why this is an enumeration.
 */
export type PublishSetting = "unset" | "in" | "out";

/**
 * Where an effective publish decision came from, so a screen can say
 * "your organization decided this" instead of showing a control that
 * silently does nothing.
 */
export type PublishSource = "instance" | "organization" | "gathering";

/**
 * The resolved publish decision for one gathering, with its reason.
 */
export interface PublishDecision {
  /**
   * Whether events under this gathering are published.
   */
  publishing: boolean;
  /**
   * The level that decided.
   */
  source: PublishSource;
  /**
   * Whether this level may still change it. False when the instance has
   * withdrawn the right to override, which is the case a UI must not
   * present as an editable control.
   */
  canOverride: boolean;
}

/**
 * Which domain owns a record, and whether that domain is this one.
 * 
 * Two instances can hold an organization with the same name, and a
 * directory can hold several at once. The NAME is not an identity; the
 * domain is. So the domain travels with every record a client can display,
 * and a client shows it — which turns "is this the group I think it is?"
 * into a question the screen has already answered.
 * 
 * This block is NOT part of a federated event. A receiving instance
 * derives it: the delivery came in, and the verified signature says which
 * domain it came from. A field inside the message could say anything the
 * sender liked, so the sender is not asked.
 */
export interface Origin {
  /**
   * The domain that owns this record.
   */
  domain: string;
  /**
   * True when `domain` is not this instance's own. A client should mark
   * these: a name that looks familiar and belongs to somebody else is
   * the case this field exists for.
   */
  isExternal: boolean;
  /**
   * The peer this record arrived from, when it is external and this
   * instance knows. Absent for anything local.
   */
  peerAddress?: string;
}

/**
 * The declared error type for every op that can fail.
 */
export interface ServiceError {
  /**
   * Application error code. Branch on this, not on `message`.
   */
  code: number;
  /**
   * Human-readable diagnostic. Safe to log; not stable enough to match on.
   */
  message: string;
  /**
   * The offending field name, when the failure is single-field validation.
   */
  field?: string;
  /**
   * What kind of resource was being looked up ("greeting", "user"), when
   * the failure is a not-found case.
   */
  resourceType?: string;
}

/**
 * Who a `users` row represents. `human` is a linkkeys-authenticated
 * person; `system` is a non-interactive actor.
 */
export type UserKind = "human" | "system";

/**
 * Request to start a login: the linkkeys domain half of the user's
 * `user@domain` identity, so the api knows which IDP to redirect to.
 */
export interface BeginLoginRequest {
  /**
   * The linkkeys domain to authenticate against (e.g. "todandlorna.com").
   */
  domain: string;
}

/**
 * Where the SPA must navigate the browser to continue the login flow. The
 * signed request inside this URL carries the self-verifying nonce.
 */
export interface BeginLoginResponse {
  /**
   * Absolute URL of the identity provider's authorize page.
   */
  redirectUrl: string;
}

/**
 * The caller's own profile, as returned by whoami. Every field is
 * server-derived, so the whole shape is receive-only.
 */
export interface UserProfile {
  id: UserID;
  linkkeysDomain: string;
  handle: string;
  displayName: string;
  kind: UserKind;
  createdAt: Date;
}

/**
 * Request to mint a session without an identity assertion. DevAuthService
 * refuses every call unless TINKU_ENV is dev or nonprod AND
 * TINKU_DEV_AUTH_ENABLED is true, so this cannot be reached in
 * production even though it is declared in the same schema.
 */
export interface DevLoginRequest {
  /**
   * The handle to log in as. The user is created on first use.
   */
  handle: string;
  /**
   * The linkkeys domain to attribute the fake identity to.
   */
  domain: string;
}

/**
 * One greeting, as stored.
 */
export interface Greeting {
  id: GreetingID;
  /**
   * Who left it. Null for greetings left by an anonymous caller.
   */
  authorId?: UserID;
  /**
   * The author's handle at the time of reading, denormalized for display.
   * Null when the greeting was left anonymously.
   */
  authorHandle?: string;
  /**
   * The greeting text.
   */
  message: string;
  createdAt: Date;
}

/**
 * Every greeting, newest first. The hello-world listing is deliberately
 * unpaginated: adding a cursor is the first thing a real service does, and
 * doing it here would obscure the shape this repo exists to demonstrate.
 */
export interface GreetingList {
  greetings: Greeting[];
}

/**
 * Leave a greeting. Requires a session; anonymous callers are refused with
 * ServiceError code 1 (unauthenticated).
 */
export interface CreateGreetingRequest {
  message: string;
}

/**
 * Fetch one greeting by id.
 */
export interface GetGreetingRequest {
  id: GreetingID;
}

/**
 * A member's standing in an organization. Owners can edit it, manage its
 * membership, and act as the organization in every place an organization
 * can own something. Members carry no authority; they are the roster.
 */
export type OrganizationRole = "owner" | "member";

/**
 * An organization, as read.
 */
export interface Organization {
  id: OrganizationID;
  /**
   * Local part of the organization's federated address, derived from the
   * name on creation and stable afterwards. Unique per origin domain.
   */
  slug: string;
  /**
   * The node that holds the authoritative row for this organization.
   */
  originDomain: string;
  name: string;
  /**
   * A short statement of what the organization is. The limit that
   * matters is 300 WORDS, which no CSIL size constraint can express —
   * the byte ceiling here only stops an abusive payload, and the server
   * counts words itself.
   */
  blurb: string;
  /**
   * The long form. Plain text; tinku does not render markup.
   */
  description: string;
  memberCount: number;
  ownerCount: number;
  /**
   * Whether this organization's gatherings publish to peer directories.
   * `unset` defers to the instance. Ignored entirely when the instance
   * has withdrawn the right to override at this level.
   */
  publishEvents: PublishSetting;
  /**
   * Which domain owns this. Always shown, so a familiar name that
   * belongs to somebody else cannot be mistaken for a local one.
   */
  origin: Origin;
  viewer: ViewerContext;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * One row of an organization's roster.
 */
export interface OrganizationMember {
  userId: UserID;
  handle: string;
  linkkeysDomain: string;
  displayName: string;
  role: OrganizationRole;
  joinedAt: Date;
}

/**
 * Start an organization. The caller becomes its first owner.
 */
export interface CreateOrganizationRequest {
  name: string;
  blurb: string;
  description: string;
}

/**
 * Change an organization. Every field is optional: an absent field is left
 * alone, which is what lets a caller send only what it edited. Owners only.
 */
export interface UpdateOrganizationRequest {
  id: OrganizationID;
  name?: string;
  blurb?: string;
  description?: string;
  publishEvents?: PublishSetting;
}

export interface GetOrganizationRequest {
  id: OrganizationID;
}

/**
 * Destroy an organization and everything that hangs off it. Admins only —
 * see the note on DeleteEventRequest for why deletion is the one power
 * reserved to the global role.
 */
export interface DeleteOrganizationRequest {
  id: OrganizationID;
}

export interface ListOrganizationsRequest {
  /**
   * Restrict to organizations the caller belongs to. Requires a session;
   * an anonymous caller asking for `mine` gets an empty list, not an
   * error.
   */
  mine?: boolean;
  /**
   * Free text. It matches the name, the blurb and the description,
   * because a person looking for the climbing organization may remember
   * what it does rather than what it is called — but a name match ranks
   * above a description match, and only the name is shown. A typeahead
   * that offered a description match with no visible reason for it
   * reads as a wrong answer.
   */
  query?: string;
  page?: Page;
}

export interface OrganizationList {
  organizations: Organization[];
  /**
   * How many rows match before paging. Lets a UI render "1-25 of 340".
   */
  total: number;
}

export interface OrganizationMemberList {
  organizationId: OrganizationID;
  members: OrganizationMember[];
  total: number;
}

export interface ListOrganizationMembersRequest {
  organizationId: OrganizationID;
  page?: Page;
}

/**
 * Add a person to an organization, or change the standing of someone
 * already on the roster. Owners only. Idempotent.
 */
export interface SetOrganizationMemberRequest {
  organizationId: OrganizationID;
  userId: UserID;
  role: OrganizationRole;
}

/**
 * Take a person off an organization's roster. Owners only, except that
 * anyone may remove themselves. An organization must keep at least one
 * owner, so removing the last one is refused.
 */
export interface RemoveOrganizationMemberRequest {
  organizationId: OrganizationID;
  userId: UserID;
}

/**
 * What an owner reference points at.
 */
export type OwnerKind = "user" | "organization";

/**
 * A person's standing in a gathering. Ownership is NOT in this enum,
 * because ownership can arrive through an organization and so is not a row
 * on the roster — read `viewer.is_owner`, or the `owners` list.
 */
export type GatheringRole = "member";

/**
 * One owner of a gathering: either an individual or an organization. `id`
 * is a UserID when kind is "user" and an OrganizationID when kind is
 * "organization"; both are ULIDs in the same space, so one field carries
 * either.
 */
export interface OwnerRef {
  kind: OwnerKind;
  id: string;
  /**
   * The owner's name for display — a user's display name, or an
   * organization's name.
   */
  displayName: string;
  /**
   * Local part of the owner's federated address: a user's handle, or an
   * organization's slug.
   */
  handle: string;
  /**
   * The owner's home node.
   */
  originDomain: string;
}

/**
 * An owner to add or remove, without the display fields the server fills in.
 */
export interface OwnerRefInput {
  kind: OwnerKind;
  id: string;
}

/**
 * A gathering, as read.
 */
export interface Gathering {
  id: GatheringID;
  /**
   * Local part of the gathering's federated address.
   */
  slug: string;
  originDomain: string;
  name: string;
  /**
   * Short statement of what this gathering is. Word-limited to 300 by
   * the server, exactly as an organization's blurb is.
   */
  blurb: string;
  description: string;
  owners: OwnerRef[];
  memberCount: number;
  /**
   * How many events and series hang off this gathering, counting a
   * series once rather than once per occurrence.
   */
  eventCount: number;
  /**
   * The next event that has not started yet, in UTC. Absent when the
   * gathering has nothing scheduled ahead of it.
   */
  nextEventAt?: Date;
  /**
   * Whether this gathering's events publish to peer directories.
   * `unset` defers to its owning organization, then to the instance.
   */
  publishEvents: PublishSetting;
  /**
   * What that resolves to, and why. The server decides; a client renders
   * the answer rather than re-deriving a three-level rule.
   */
  publish: PublishDecision;
  /**
   * Which domain owns this. Always shown, so a familiar name that
   * belongs to somebody else cannot be mistaken for a local one.
   */
  origin: Origin;
  viewer: ViewerContext;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * One row of a gathering's roster. Owners appear here only when they own
 * the gathering directly AND joined it; an organization's owner who never
 * joined is an owner without being a member, which is why `viewer.is_owner`
 * and `viewer.is_member` are separate flags.
 */
export interface GatheringMember {
  userId: UserID;
  handle: string;
  linkkeysDomain: string;
  displayName: string;
  joinedAt: Date;
}

/**
 * Start a gathering. When `owner` is absent the caller becomes its sole
 * individual owner; when it names an organization, the caller must own
 * that organization.
 */
export interface CreateGatheringRequest {
  name: string;
  blurb: string;
  description: string;
  owner?: OwnerRefInput;
}

export interface UpdateGatheringRequest {
  id: GatheringID;
  name?: string;
  blurb?: string;
  description?: string;
  publishEvents?: PublishSetting;
}

export interface GetGatheringRequest {
  id: GatheringID;
}

/**
 * Destroy a gathering and every event under it. An owner may do this, and
 * so may an admin — unlike an organization, which only an admin can
 * destroy.
 */
export interface DeleteGatheringRequest {
  id: GatheringID;
}

export interface ListGatheringsRequest {
  /**
   * Only gatherings the caller belongs to or owns.
   */
  mine?: boolean;
  /**
   * Only gatherings this organization owns.
   */
  ownedByOrganization?: OrganizationID;
  page?: Page;
}

export interface GatheringList {
  gatherings: Gathering[];
  total: number;
}

export interface ListGatheringMembersRequest {
  gatheringId: GatheringID;
  page?: Page;
}

export interface GatheringMemberList {
  gatheringId: GatheringID;
  members: GatheringMember[];
  total: number;
}

/**
 * Join a gathering. Any authenticated caller may join any gathering;
 * membership is what makes marking attendance on its events possible.
 * Idempotent.
 */
export interface JoinGatheringRequest {
  gatheringId: GatheringID;
}

/**
 * Leave a gathering. Idempotent. Leaving does not withdraw attendance
 * already marked on events that have started, because a started event
 * cannot be changed at all.
 */
export interface LeaveGatheringRequest {
  gatheringId: GatheringID;
}

/**
 * Add an owner — an individual or an organization — to a gathering.
 * Existing owners only. Adding an organization requires the caller to own
 * it, so that ownership cannot be handed to a set of people who did not
 * agree to it.
 */
export interface AddGatheringOwnerRequest {
  gatheringId: GatheringID;
  owner: OwnerRefInput;
}

/**
 * Drop an owner. A gathering must keep at least one owner, so removing
 * the last one is refused.
 */
export interface RemoveGatheringOwnerRequest {
  gatheringId: GatheringID;
  owner: OwnerRefInput;
}

/**
 * Where an offer stands. An offer is a two-sided move: a gathering's owner
 * hands it to an organization, and an owner of that organization accepts.
 * Neither side can do it alone — an owner cannot push a gathering into
 * somebody else's organization, and an organization cannot take one.
 */
export type GatheringOfferStatus = "pending" | "accepted" | "declined" | "withdrawn";

/**
 * One offer of one gathering to one organization.
 */
export interface GatheringOffer {
  id: GatheringOfferID;
  gatheringId: GatheringID;
  gatheringName: string;
  organizationId: OrganizationID;
  organizationName: string;
  /**
   * Who offered it. The gathering's owner at the time of the offer.
   */
  offeredBy: UserRef;
  /**
   * Why, in the offerer's words. An organization's owner is being asked
   * to take on somebody else's gathering and deserves a sentence about
   * it.
   */
  note: string;
  status: GatheringOfferStatus;
  createdAt: Date;
  /**
   * When it stopped being pending. Absent while it still is.
   */
  resolvedAt?: Date;
  viewer: ViewerContext;
}

/**
 * Offer a gathering to an organization. The caller must own the
 * gathering. Offering the same gathering to the same organization twice
 * while an offer is pending returns the pending one rather than making a
 * second.
 */
export interface OfferGatheringRequest {
  gatheringId: GatheringID;
  organizationId: OrganizationID;
  note: string;
}

/**
 * Offers to an organization the caller owns, or offers of a gathering the
 * caller owns. With neither field, every offer the caller can see.
 */
export interface ListGatheringOffersRequest {
  organizationId?: OrganizationID;
  gatheringId?: GatheringID;
  /**
   * Include offers that are no longer pending. Off by default.
   */
  includeResolved?: boolean;
}

export interface GatheringOfferList {
  offers: GatheringOffer[];
  total: number;
}

/**
 * Accept or decline. An owner of the organization only.
 * 
 * Accepting makes the organization an owner of the gathering ALONGSIDE
 * whoever owned it before — an offer is not a surrender — and puts the
 * gathering's individual owners on the organization's roster, since they
 * now hold ownership through it. The gathering's members are not touched:
 * people join gatherings and attend events, and nobody is enrolled into an
 * organization by a decision two other people made.
 */
export interface RespondToGatheringOfferRequest {
  offerId: GatheringOfferID;
  accept: boolean;
}

/**
 * Take back an offer that is still pending. The offering side only.
 */
export interface WithdrawGatheringOfferRequest {
  offerId: GatheringOfferID;
}

/**
 * Put a gathering under an organization with no offer and no acceptance.
 * Administrators only: this is the tool for a gathering that was started
 * loose and belongs to an organization that already exists, and it is
 * deliberately not available to anybody who could otherwise be tempted to
 * take a gathering that is not theirs.
 */
export interface AdoptGatheringRequest {
  gatheringId: GatheringID;
  organizationId: OrganizationID;
}

/**
 * A day of the week, spelled in English regardless of the caller's locale
 * — this is a wire value, not display text. The UI translates it.
 */
export type Weekday = "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";

/**
 * The period a recurrence rule repeats over.
 */
export type RecurrenceFreq = "weekly" | "monthly" | "quarterly" | "yearly";

/**
 * When a series happens. One rule per series; a gathering that needs
 * "every second Thursday" AND "every fourth Wednesday" holds two series,
 * which is why multiple series in one gathering is the normal case rather
 * than an edge case.
 * 
 * The three worked examples from the domain:
 * 
 * every second Thursday   -> freq monthly,   interval 1, ordinal 2,  weekday thursday
 * every fourth Wednesday  -> freq monthly,   interval 1, ordinal 4,  weekday wednesday
 * first Saturday of the quarter
 * -> freq quarterly, interval 1, ordinal 1,  weekday saturday
 * 
 * "Every other Thursday" is the weekly form instead: freq weekly,
 * interval 2, weekday thursday. The ordinal reading of "every second
 * Thursday" (the 2nd Thursday of each month) and the interval reading
 * (every 14 days) are both expressible, and they are different rules.
 */
export interface RecurrenceRule {
  freq: RecurrenceFreq;
  /**
   * Repeat every N periods. 1 means every period. Zero is read as 1.
   */
  interval: number;
  /**
   * Which weekday the occurrence lands on. Required for every freq
   * except a monthly rule that uses `day_of_month` instead.
   */
  weekday?: Weekday;
  /**
   * Which occurrence of `weekday` within the period: 1 through 5, or -1
   * for the last one. Required for monthly, quarterly and yearly rules
   * that use `weekday`; meaningless for weekly rules, which have exactly
   * one of each weekday per period.
   * 
   * An ordinal of 5 in a period that has only four of that weekday
   * produces no occurrence for that period. It is not an error and it is
   * not rounded down to the fourth — a rule that says "the fifth
   * Thursday" means the fifth one.
   */
  ordinal?: number;
  /**
   * Day of the month, 1-31, as an alternative to weekday + ordinal.
   * A day past the end of a short month produces no occurrence for that
   * month, for the same reason.
   */
  dayOfMonth?: number;
}

/**
 * Where an in-person event is. Every field is optional so a location can
 * be as vague as a city or as exact as a street address; the server only
 * insists that an in-person event have SOMETHING here.
 * 
 * Coordinates drive proximity search. They are plain columns compared as
 * numbers, not a geometry type, because the same schema has to run on
 * SQLite as well as Postgres — see docs/OPERATING.md.
 */
export interface Location {
  /**
   * Name of the venue ("Ada Lovelace Library").
   */
  name: string;
  /**
   * Street address, one line.
   */
  address: string;
  /**
   * City or town.
   */
  locality: string;
  /**
   * State, province or equivalent.
   */
  region: string;
  postalCode: string;
  /**
   * ISO 3166-1 alpha-2, uppercase.
   */
  country: string;
  latitude?: number;
  longitude?: number;
}

/**
 * One event: a single dated thing, whether it stands alone or is an
 * occurrence of a series.
 */
export interface Event {
  id: EventID;
  gatheringId: GatheringID;
  /**
   * The series this occurrence came from, absent for a standalone event.
   */
  seriesId?: EventSeriesID;
  title: string;
  /**
   * Absent once the event has started — see the start-time lock above.
   * Absent and empty are the same thing to a reader, which is why the
   * lock can be implemented by simply not sending it.
   */
  description?: string;
  /**
   * An event can be online, in person, or both. At least one must be
   * true, and in-person requires a location.
   */
  isOnline: boolean;
  isInPerson: boolean;
  /**
   * Where to attend online. Withheld exactly as `description` is once
   * the event has started.
   */
  onlineUrl?: string;
  location?: Location;
  startsAt: Date;
  endsAt: Date;
  /**
   * IANA name of the zone the event was scheduled in ("America/Denver").
   * `starts_at` is the authoritative instant; this is what a UI needs to
   * say "7pm local" and mean the organizer's local, not the reader's.
   */
  timezone: string;
  /**
   * True once `starts_at` has passed. Frozen: no edits, no attendance
   * change, no description.
   */
  locked: boolean;
  attendeeCount: number;
  viewerAttending: boolean;
  /**
   * Which domain owns this. Always shown, so a familiar name that
   * belongs to somebody else cannot be mistaken for a local one.
   */
  origin: Origin;
  viewer: ViewerContext;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * A recurring set of events: the template fields, plus the rule, plus the
 * window the rule applies over. Editing a series rewrites its future
 * occurrences and leaves started ones alone — a started event is frozen,
 * and being produced by a rule does not exempt it.
 */
export interface EventSeries {
  id: EventSeriesID;
  gatheringId: GatheringID;
  title: string;
  description: string;
  isOnline: boolean;
  isInPerson: boolean;
  onlineUrl?: string;
  location?: Location;
  recurrence: RecurrenceRule;
  /**
   * First date the rule may produce an occurrence on, as a UTC instant
   * at midnight of the local date.
   */
  startsOn: Date;
  /**
   * Last date the rule may produce an occurrence on. Absent means the
   * series is open-ended, and the api keeps a bounded horizon
   * materialized rather than an infinite one.
   */
  endsOn?: Date;
  /**
   * Local clock time each occurrence begins, "HH:MM" on a 24-hour clock,
   * interpreted in `timezone`.
   * 
   * WHY THIS IS NOT UTC, when every other time in tinku is: this pair is
   * the RULE, not a time. "The second Thursday at 19:00 in Denver" is
   * 01:00 UTC in September and 02:00 UTC in November — one rule, two UTC
   * answers — so holding it as UTC would make it wrong twice a year. The
   * instants the rule PRODUCES are stored in UTC like everything else.
   */
  startTime: string;
  /**
   * How long each occurrence runs.
   */
  durationMinutes: number;
  timezone: string;
  /**
   * How many occurrences are materialized right now.
   */
  occurrenceCount: number;
  /**
   * When the next occurrence that has not started begins. Absent for a
   * series whose materialized occurrences have all started.
   */
  nextOccurrenceAt?: Date;
  /**
   * Which domain owns this. Always shown, so a familiar name that
   * belongs to somebody else cannot be mistaken for a local one.
   */
  origin: Origin;
  viewer: ViewerContext;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * A role held on one event or on one series. Ownership is not here: owners
 * are a property of the GATHERING and reach every event under it.
 * 
 * A presenter carries exactly a member's permissions today. The role is
 * stored anyway because who presents is information the gathering wants to
 * show, and because giving presenters their own permissions later should
 * not need a migration.
 */
export type EventRole = "organizer" | "presenter";

/**
 * One person holding a role on an event or a series.
 */
export interface EventRoleAssignment {
  eventId?: EventID;
  seriesId?: EventSeriesID;
  userId: UserID;
  handle: string;
  linkkeysDomain: string;
  displayName: string;
  role: EventRole;
  assignedAt: Date;
}

/**
 * One person who said they are attending.
 */
export interface Attendee {
  userId: UserID;
  handle: string;
  linkkeysDomain: string;
  displayName: string;
  markedAt: Date;
}

export interface CreateEventRequest {
  gatheringId: GatheringID;
  title: string;
  description: string;
  isOnline: boolean;
  isInPerson: boolean;
  onlineUrl?: string;
  location?: Location;
  startsAt: Date;
  endsAt: Date;
  timezone: string;
}

/**
 * Change an event. Absent fields are left alone. Refused once the event
 * has started.
 */
export interface UpdateEventRequest {
  id: EventID;
  title?: string;
  description?: string;
  isOnline?: boolean;
  isInPerson?: boolean;
  onlineUrl?: string;
  location?: Location;
  startsAt?: Date;
  endsAt?: Date;
  timezone?: string;
}

export interface GetEventRequest {
  id: EventID;
}

/**
 * Destroy one event. A gathering owner or an event organizer may delete an
 * event that has not started. An event that HAS started is history, and
 * only an admin can remove history.
 */
export interface DeleteEventRequest {
  id: EventID;
}

/**
 * List events, newest start first for past windows and soonest first for
 * future ones. With no time bounds the api returns events that have not
 * ended, which is what a calendar view wants.
 */
export interface ListEventsRequest {
  gatheringId?: GatheringID;
  /**
   * Only events under gatherings this organization owns.
   */
  ownedByOrganization?: OrganizationID;
  /**
   * Only events under gatherings the caller belongs to or owns. Requires
   * a session; an anonymous caller asking for `mine` gets an empty list.
   * 
   * This is a WIDER question than `attending_only`: what is on for the
   * groups I am part of, rather than what I have said I am coming to.
   */
  mine?: boolean;
  /**
   * Only events starting at or after this instant.
   */
  startsAfter?: Date;
  /**
   * Only events starting at or before this instant.
   */
  startsBefore?: Date;
  /**
   * Only events the caller has marked attendance on. Requires a session.
   */
  attendingOnly?: boolean;
  /**
   * Include events that have already started. Off by default.
   */
  includeStarted?: boolean;
  page?: Page;
}

export interface EventList {
  events: Event[];
  total: number;
}

export interface CreateEventSeriesRequest {
  gatheringId: GatheringID;
  title: string;
  description: string;
  isOnline: boolean;
  isInPerson: boolean;
  onlineUrl?: string;
  location?: Location;
  recurrence: RecurrenceRule;
  startsOn: Date;
  endsOn?: Date;
  startTime: string;
  durationMinutes: number;
  timezone: string;
}

/**
 * Change a series. Rewrites every occurrence that has not started; the
 * ones that have are left exactly as they are.
 */
export interface UpdateEventSeriesRequest {
  id: EventSeriesID;
  title?: string;
  description?: string;
  isOnline?: boolean;
  isInPerson?: boolean;
  onlineUrl?: string;
  location?: Location;
  recurrence?: RecurrenceRule;
  startsOn?: Date;
  endsOn?: Date;
  startTime?: string;
  durationMinutes?: number;
  timezone?: string;
}

export interface GetEventSeriesRequest {
  id: EventSeriesID;
}

/**
 * Destroy a series and every one of its occurrences that has not started.
 * Occurrences that have started survive, detached from the rule, because
 * they are history and deleting history is an admin's power alone.
 */
export interface DeleteEventSeriesRequest {
  id: EventSeriesID;
}

export interface ListEventSeriesRequest {
  gatheringId?: GatheringID;
  page?: Page;
}

export interface EventSeriesList {
  series: EventSeries[];
  total: number;
}

/**
 * Materialize this series' occurrences out to `through`, then return every
 * occurrence it now has. Idempotent: occurrences already on disk are left
 * alone, so calling this twice does not duplicate anything.
 */
export interface ExpandEventSeriesRequest {
  seriesId: EventSeriesID;
  /**
   * How far to materialize. Clamped to the api's maximum horizon.
   */
  through?: Date;
}

/**
 * Mark the caller as attending. Requires membership of the event's
 * gathering, and refused once the event has started. Idempotent.
 */
export interface AttendEventRequest {
  eventId: EventID;
}

/**
 * Withdraw the caller's attendance. Refused once the event has started.
 * Idempotent.
 */
export interface UnattendEventRequest {
  eventId: EventID;
}

export interface ListAttendeesRequest {
  eventId: EventID;
  page?: Page;
}

export interface AttendeeList {
  eventId: EventID;
  attendees: Attendee[];
  total: number;
}

/**
 * Give someone a role on one event or one series. Exactly one of
 * `event_id` and `series_id` must be set. Gathering owners only.
 * Idempotent.
 */
export interface SetEventRoleRequest {
  eventId?: EventID;
  seriesId?: EventSeriesID;
  userId: UserID;
  role: EventRole;
}

/**
 * Take a role away. Exactly one of `event_id` and `series_id` must be set.
 */
export interface RemoveEventRoleRequest {
  eventId?: EventID;
  seriesId?: EventSeriesID;
  userId: UserID;
  role: EventRole;
}

export interface ListEventRolesRequest {
  eventId?: EventID;
  seriesId?: EventSeriesID;
}

export interface EventRoleList {
  roles: EventRoleAssignment[];
}

/**
 * What kind of thing a search should return. An empty `kinds` list means
 * every kind.
 */
export type SearchKind = "organization" | "gathering" | "event" | "series" | "remote-event";

/**
 * A circle on the earth's surface.
 */
export interface GeoCircle {
  latitude: number;
  longitude: number;
  /**
   * Radius in kilometres. Clamped to the api's maximum.
   */
  radiusKm: number;
}

/**
 * Filter results by place. Every field is independent: naming a locality
 * and a circle requires a result to satisfy both.
 * 
 * Text place fields match case-insensitively on equality, not on
 * substring — "Denver" must be the locality, not appear inside it.
 */
export interface LocationFilter {
  locality?: string;
  region?: string;
  country?: string;
  near?: GeoCircle;
}

export interface SearchRequest {
  /**
   * Free text, matched case-insensitively against names, titles, blurbs
   * and descriptions. Absent or empty matches everything, which is how
   * a pure browse-by-place or browse-by-time query is expressed.
   */
  query?: string;
  /**
   * Restrict to these kinds. Empty or absent means every kind.
   */
  kinds?: SearchKind[];
  location?: LocationFilter;
  /**
   * Only events and series with an occurrence starting at or after this.
   * Ignored for organizations, which have no time.
   */
  startsAfter?: Date;
  /**
   * Only events and series with an occurrence starting at or before this.
   */
  startsBefore?: Date;
  /**
   * Only things that can be attended online.
   */
  onlineOnly?: boolean;
  /**
   * Only things that happen in person.
   */
  inPersonOnly?: boolean;
  /**
   * Include events that have already started. Off by default, because
   * the common search is for something still to come.
   */
  includeStarted?: boolean;
  /**
   * Applied to each kind independently, so asking for 25 results with no
   * `kinds` filter can return 25 of each.
   */
  page?: Page;
}

/**
 * What a search found, grouped by kind. A kind excluded by the request, or
 * with no matches, comes back as an empty list rather than being absent —
 * one shape for the client to render regardless of what matched.
 */
export interface SearchResults {
  organizations: Organization[];
  gatherings: Gathering[];
  events: Event[];
  series: EventSeries[];
  /**
   * Events peers sent, when this instance is a directory. They are a
   * separate list rather than mixed into `events` because they are a
   * different thing: a summary and a link, with nothing here to attend
   * and nobody here able to edit them.
   */
  remoteEvents: RemoteEvent[];
  /**
   * Total matches per kind before paging, in the order organizations,
   * gatherings, events, series.
   */
  organizationTotal: number;
  gatheringTotal: number;
  eventTotal: number;
  seriesTotal: number;
  remoteEventTotal: number;
}

/**
 * A person holding the global admin role.
 */
export interface AdminUser {
  userId: UserID;
  handle: string;
  linkkeysDomain: string;
  displayName: string;
  grantedAt: Date;
}

export interface AdminList {
  admins: AdminUser[];
}

/**
 * Grant or revoke the global admin role. Admins only. Revoking the last
 * admin is refused: a deployment with no admin has no way to delete an
 * organization and no way to make an admin again.
 */
export interface SetAdminRequest {
  userId: UserID;
  /**
   * True to grant, false to revoke.
   */
  granted: boolean;
}

/**
 * Look a person up by their federated address, so an admin can grant the
 * role without having to learn a ULID first.
 */
export interface FindUserRequest {
  handle: string;
  domain: string;
}

/**
 * A person, as an admin or a roster editor sees them.
 */
export interface UserRef {
  userId: UserID;
  handle: string;
  linkkeysDomain: string;
  displayName: string;
  isAdmin: boolean;
}

export interface UserRefList {
  users: UserRef[];
}

/**
 * Search people by handle prefix, so member pickers can offer completions.
 */
export interface SearchUsersRequest {
  query: string;
  page?: Page;
}

/**
 * Settings an administrator changes while the service runs. They live in
 * the database rather than the environment, so a change needs no restart
 * and every replica sees the same value.
 */
export interface InstanceSettings {
  /**
   * What a gathering publishes when nothing below has said otherwise.
   * Defaults to `in`: an instance that has switched federation on and
   * approved a directory has already made the interesting choice.
   */
  publishDefault: PublishSetting;
  /**
   * Whether an organization may override the instance default.
   */
  organizationOverrideAllowed: boolean;
  /**
   * Whether a gathering may override what is above it.
   */
  gatheringOverrideAllowed: boolean;
  /**
   * How long a directory keeps what a peer sent, after the event ends.
   * Zero keeps everything.
   */
  retentionDays: number;
  /**
   * How many events one peer may have accepted per minute. Zero means no
   * limit. A peer that exceeds it has the rest of its batch refused,
   * which is what stops a peer that has lost control of itself from
   * filling this instance's directory.
   */
  peerRateLimitPerMinute: number;
  /**
   * How many events one ORGANIZATION inside a peer may have accepted per
   * minute. Zero means no limit.
   * 
   * The limit exists at both levels because a peer's allowance is
   * shared. Without this one, a single organization inside a peer can
   * spend the whole budget, and that peer's other organizations are then
   * refused for something they did not do. Set it below the peer limit
   * or it has no effect.
   */
  originRateLimitPerMinute: number;
}

/**
 * Change one or more settings. An absent field is left alone.
 */
export interface UpdateInstanceSettingsRequest {
  publishDefault?: PublishSetting;
  organizationOverrideAllowed?: boolean;
  gatheringOverrideAllowed?: boolean;
  retentionDays?: number;
  peerRateLimitPerMinute?: number;
  originRateLimitPerMinute?: number;
}

/**
 * A peer's standing in one direction.
 * 
 * `none` is the resting state: no agreement either way. `pending` is a
 * request an administrator has not answered. `blocked` is a decision, and
 * differs from `none` in that it survives a further request.
 */
export type PeerStatus = "none" | "pending" | "approved" | "blocked";

/**
 * Another instance, as this one sees it.
 */
export interface Peer {
  id: string;
  /**
   * The peer's account address, `handle@domain`. This is the identity a
   * signature is checked against, not the URL it is reached at — a peer
   * that moves host keeps its name.
   */
  address: string;
  handle: string;
  domain: string;
  /**
   * The peer's canonical linkkeys identity: one account, one
   * application, one application instance. Resolved and stored the first
   * time a signed request from this address verifies, or set by an
   * administrator at approval time. Empty until then.
   * 
   * This, not `address`, is what a delivery is actually checked against.
   * A handle can move to a different account or be reused; this cannot,
   * because it is bound by a cryptographic signature, not merely typed
   * in.
   */
  subjectUserId?: string;
  subjectDomain?: string;
  applicationId?: string;
  instanceId?: string;
  /**
   * Where to reach this peer's CSIL-RPC endpoint, and the base a
   * canonical event link is resolved against.
   */
  baseUrl: string;
  /**
   * Do we accept what this peer sends us.
   */
  inboundStatus: PeerStatus;
  /**
   * Do we deliver our events to this peer.
   */
  outboundStatus: PeerStatus;
  /**
   * An administrator's own note about why this peer is here.
   */
  note: string;
  /**
   * True when delivery to this peer has stopped. Retries do not resume
   * on their own — an administrator has to restart the peer, which is
   * the point: a peer that has been failing for a day is a thing a
   * person should look at, not a thing to keep hammering.
   */
  suspended: boolean;
  suspendedAt?: Date;
  /**
   * When the current run of failures began. Absent once a delivery
   * succeeds, because the run is over.
   */
  firstFailureAt?: Date;
  lastFailureAt?: Date;
  /**
   * What went wrong last, for an administrator to read. Never matched on.
   */
  lastFailureReason: string;
  lastSuccessAt?: Date;
  /**
   * How many deliveries are waiting for this peer.
   */
  pendingDeliveries: number;
  /**
   * How many events a minute this peer may have accepted. Absent means
   * the instance-wide limit applies.
   */
  rateLimitPerMinute?: number;
  /**
   * How many events this peer has ever had refused for exceeding its
   * allowance. An administrator needs to see that a peer is being
   * throttled, not merely that it has gone quiet.
   */
  rateLimitedTotal: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface PeerList {
  peers: Peer[];
  total: number;
}

export interface ListPeersRequest {
  page?: Page;
}

/**
 * Register another instance as a directory to publish to, and ask it to
 * accept us. Administrators only. Sets our outbound status to `pending`
 * until the peer answers.
 */
export interface AddPeerRequest {
  /**
   * The peer's account address, `handle@domain`.
   */
  address: string;
  /**
   * The peer's base URL.
   */
  baseUrl: string;
  note: string;
}

/**
 * Answer a peer's request, or change our mind about one. Administrators
 * only. An absent status is left as it is.
 * 
 * The four identity fields are all-or-nothing: give none to leave the
 * peer's stored identity as it is, or give all four to set or replace it.
 * Approving inbound requires the peer to already have an identity, or for
 * this request to supply one — see the note on `Peer.subject_user_id`.
 */
export interface SetPeerStatusRequest {
  peerId: string;
  inboundStatus?: PeerStatus;
  outboundStatus?: PeerStatus;
  subjectUserId?: string;
  subjectDomain?: string;
  applicationId?: string;
  instanceId?: string;
}

/**
 * Restart delivery to a suspended peer. Administrators only. Clears the
 * failure run and makes every waiting delivery due immediately.
 */
export interface ResumePeerRequest {
  peerId: string;
}

/**
 * Give one peer its own allowance, or take it away. Administrators only.
 * An absent limit restores the instance-wide one.
 */
export interface SetPeerRateLimitRequest {
  peerId: string;
  rateLimitPerMinute?: number;
}

/**
 * Forget a peer and everything it sent. Administrators only.
 */
export interface RemovePeerRequest {
  peerId: string;
}

/**
 * One event as it travels between instances: a summary and a link.
 * 
 * There is no description and no attendance. A reader who wants either
 * follows `canonical_url` to the instance that owns the event, which is
 * the only place either is true.
 */
export interface FederatedEvent {
  /**
   * The event's id at its origin. Unique per peer, and the key an
   * update or a deletion refers to.
   */
  remoteId: string;
  /**
   * Absolute URL of the event at its origin.
   */
  canonicalUrl: string;
  title: string;
  isOnline: boolean;
  isInPerson: boolean;
  location?: Location;
  startsAt: Date;
  endsAt: Date;
  timezone: string;
  /**
   * Display context, so a directory can say what this event belongs to
   * without a second call.
   */
  gatheringName: string;
  organizationName: string;
  /**
   * True when this is a tombstone: the origin deleted the event and the
   * directory should forget it. A deletion has to travel as a message
   * like any other, because a directory cannot tell absence from silence.
   */
  deleted: boolean;
}

/**
 * The decoded contents of a delivery. This is what `SignedDelivery.body`
 * holds once its signature has been checked.
 */
export interface EventBatch {
  /**
   * Where these came from. Checked against the verified signer, so a
   * batch cannot claim an origin its signature does not support.
   */
  originDomain: string;
  /**
   * A value the sender never repeats. The receiver remembers it, so a
   * captured delivery replayed later is refused rather than applied a
   * second time.
   * 
   * A signature alone cannot stop a replay: it stays valid forever, so
   * an old envelope resent would silently revert a peer's newer update,
   * and an old tombstone would delete an event that was republished.
   */
  batchId: string;
  /**
   * When the sender made this batch. The receiver refuses one that is
   * too old or too far ahead, which is what bounds how long it must
   * remember a batch_id.
   */
  sentAt: Date;
  events: FederatedEvent[];
}

/**
 * A batch of events, signed by the instance that sends it.
 * 
 * This op is called BY another instance, not by a person, and carries no
 * session. The signature is the authentication.
 */
export interface SignedDelivery {
  /**
   * Who signed, as `handle@domain`.
   */
  senderAddress: string;
  /**
   * Names the signing scheme, so a scheme can be added without a new op
   * and an old one can be refused by name.
   */
  algorithm: string;
  /**
   * Which of the sender's currently valid signing keys made this
   * signature. All of a sender's valid keys are equal — there is no
   * preferred one — so the receiver needs this to know which public key
   * to check the signature against.
   */
  keyId: string;
  signature: string;
  /**
   * The CBOR encoding of an EventBatch. Verified as bytes, then decoded
   * — see the note at the top of this file.
   */
  body: Uint8Array;
}

/**
 * What a directory answers a delivery with.
 */
export interface DeliveryReceipt {
  accepted: number;
  /**
   * How many were refused: a tombstone for something never held, an
   * event outside the window a directory keeps, a malformed row.
   */
  rejected: number;
  /**
   * Why, when anything was refused. For an operator to read.
   */
  message?: string;
  /**
   * How many were refused specifically for exceeding this peer's
   * allowance. Reported separately so a sender can tell "you are sending
   * too fast" from "that row was malformed" and slow down rather than
   * retry.
   */
  rateLimited: number;
}

/**
 * The decoded contents of a peering request.
 */
export interface PeeringBody {
  baseUrl: string;
  note: string;
  requestedAt: Date;
}

/**
 * Ask a directory to accept us. Called BY another instance and signed, the
 * same way a delivery is. The directory records it as `pending`; an
 * administrator there decides.
 * 
 * Unlike a delivery, the sender is usually unknown here — this may be the
 * first the directory has ever heard of it, so there is no stored peer row
 * to check the signature against yet. The four identity fields carry the
 * sender's canonical linkkeys identity in the envelope, alongside
 * `sender_address`, so the directory can look up the sender's attested
 * keys and verify the signature before it has ever seen this sender
 * before. They are checked as received, the same as everything else in
 * this envelope — never taken from the decoded body, which is verified
 * only after the signature over it has already passed.
 */
export interface SignedPeeringRequest {
  senderAddress: string;
  algorithm: string;
  keyId: string;
  subjectUserId: string;
  subjectDomain: string;
  applicationId: string;
  instanceId: string;
  signature: string;
  body: Uint8Array;
}

/**
 * What a directory answers a peering request with. `pending` is the normal
 * answer: nobody is admitted without an administrator.
 */
export interface PeeringReceipt {
  status: PeerStatus;
}

/**
 * One event held on behalf of a peer. It is deliberately NOT an Event: it
 * has no gathering here, nobody can edit it, nobody can attend it, and it
 * carries no permissions. Giving it the same type would mean every rule
 * that holds for a local event would have to be re-checked for one that
 * cannot obey it.
 */
export interface RemoteEvent {
  id: string;
  /**
   * The peer that sent it.
   */
  peerAddress: string;
  /**
   * Always external, by construction: a foreign event is a RemoteEvent
   * and never an Event. The block is here anyway so a client rendering a
   * mixed list has one shape to read rather than two.
   */
  origin: Origin;
  originDomain: string;
  remoteId: string;
  /**
   * Where to read the whole thing.
   */
  canonicalUrl: string;
  title: string;
  isOnline: boolean;
  isInPerson: boolean;
  location?: Location;
  startsAt: Date;
  endsAt: Date;
  timezone: string;
  gatheringName: string;
  organizationName: string;
  receivedAt: Date;
}

export interface RemoteEventList {
  events: RemoteEvent[];
  total: number;
}

export interface ListRemoteEventsRequest {
  query?: string;
  startsAfter?: Date;
  startsBefore?: Date;
  page?: Page;
}

/**
 * What this instance is, as a peer would address it. Anyone may read it:
 * it is the information somebody needs in order to ask for peering, and
 * it is not a secret — it is a name.
 */
export interface FederationIdentity {
  /**
   * This instance's account address, `handle@domain`. Empty when
   * federation is switched off.
   */
  address: string;
  /**
   * Whether this instance federates at all.
   */
  enabled: boolean;
  /**
   * The signing scheme this instance uses.
   */
  algorithm: string;
  /**
   * This instance's canonical linkkeys identity. A peer records these,
   * not just `address`, so its approval of this instance survives a
   * handle change. Empty when federation is switched off.
   */
  subjectUserId: string;
  subjectDomain: string;
  applicationId: string;
  instanceId: string;
}

/**
 * How much one originating organization is sending, and what its peer's
 * throttle is doing.
 * 
 * The limit is enforced per PEER — a peer is what a signature identifies
 * and what can be suspended. A peer carries many organizations, so
 * "this peer is throttled" does not say which origin is responsible. This
 * is the row that does.
 */
export interface OriginVolume {
  peerId: string;
  peerAddress: string;
  /**
   * The name as the peer sent it. Display text from another instance,
   * not a key into anything here. Empty when the far end had no owning
   * organization to name.
   */
  organizationName: string;
  /**
   * Events from this organization the directory currently holds.
   */
  held: number;
  /**
   * Events ever accepted from it.
   */
  acceptedTotal: number;
  /**
   * Events accepted in the current minute, measured the same way the
   * peer's own limiter measures, so the two numbers on one screen mean
   * the same thing.
   */
  acceptedThisMinute: number;
  lastReceivedAt?: Date;
  /**
   * The peer's allowance and throttle state, carried here so an operator
   * reading this list does not have to cross-reference the peer list to
   * find out whether the volume is being refused.
   */
  peerRateLimitPerMinute: number;
  peerRateLimitedTotal: number;
  peerSuspended: boolean;
  /**
   * This origin's own allowance. Absent means the instance-wide origin
   * limit applies.
   */
  rateLimitPerMinute?: number;
  /**
   * The allowance actually in force, after the override is resolved.
   * Sent so a screen does not have to repeat the resolution.
   */
  effectiveRateLimitPerMinute: number;
  /**
   * Events refused for exceeding THIS origin's allowance, as distinct
   * from the peer's.
   */
  rateLimitedTotal: number;
}

/**
 * Give one origin its own allowance, or take it away. Administrators only.
 * An absent limit restores the instance-wide one.
 */
export interface SetOriginRateLimitRequest {
  peerId: string;
  organizationName: string;
  rateLimitPerMinute?: number;
}

export interface OriginVolumeList {
  origins: OriginVolume[];
  total: number;
}

/**
 * Busiest first. Narrow to one peer to answer "which of this peer's
 * organizations is the noisy one".
 */
export interface ListOriginVolumeRequest {
  peerId?: string;
  page?: Page;
}

/**
 * What a webhook hangs off. An event or a series never carries one of its
 * own: a webhook is set where a person holds ownership, and the things
 * underneath it are what it reports on.
 */
export type WebhookOwnerKind = "organization" | "gathering";

/**
 * How much of what happens underneath is reported.
 * 
 * `all` is everything under the level, events included. `structure_only`
 * is the organization and its gatherings, and no events at all — the
 * setting for an integration that tracks WHAT EXISTS rather than what is
 * scheduled. On a gathering, the two differ only in whether its events are
 * reported, since a gathering has no gatherings under it.
 */
export type WebhookScope = "all" | "structure_only";

/**
 * What happened. A cancellation is not a deletion: a cancelled event still
 * exists and still shows, which a receiver has to be able to tell apart
 * from a record that went away.
 */
export type WebhookAction = "created" | "updated" | "cancelled" | "deleted";

/**
 * What it happened to.
 */
export type WebhookSubject = "organization" | "gathering" | "event" | "series";

/**
 * A webhook, as read. The secret is NOT here: it is returned once, by
 * create-webhook, and never again — a value a server can hand back on
 * demand is a value that leaks through any screen that shows it.
 */
export interface Webhook {
  id: WebhookID;
  ownerKind: WebhookOwnerKind;
  ownerId: string;
  /**
   * Where deliveries are POSTed. HTTPS only, except in a dev
   * environment, where a local http:// endpoint is the only way to try
   * one at all.
   */
  url: string;
  scope: WebhookScope;
  /**
   * A webhook that fails repeatedly is switched off rather than retried
   * forever. An owner switches it back on after fixing the endpoint.
   */
  active: boolean;
  /**
   * Send the record, not only a pointer to it.
   * 
   * Off by default, and the default is the safe one: a delivery goes to
   * a URL over which this server has no say, and a gathering's
   * description or an address can be information its members did not
   * expect to travel. With this on, a delivery carries the fields a
   * reader of the record would see — description, times, location, link.
   * 
   * It is the OWNER's information to send. They are the same people who
   * wrote it, and a directory that refused to tell them their own
   * description would be pretending to a control it does not have. The
   * client warns and asks them to accept it; the server records the
   * choice.
   */
  includeDetails: boolean;
  /**
   * What this webhook is for, in the owner's own words. Shown in the
   * list, so five of them are tellable apart.
   */
  note: string;
  /**
   * What the last attempt did. Absent until one has been made.
   */
  lastStatus?: number;
  lastAttemptAt?: Date;
  /**
   * Consecutive failures. Reset by a success, and by an owner switching
   * the webhook back on.
   */
  failureCount: number;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * A webhook and the signing secret that was minted with it. This shape is
 * returned by create-webhook alone.
 */
export interface WebhookWithSecret {
  webhook: Webhook;
  /**
   * The HMAC-SHA256 key that signs every delivery to this webhook, in
   * the `X-Tinku-Signature` header. Shown once. A receiver that does not
   * check it cannot tell a delivery from anybody else's POST.
   */
  secret: string;
}

export interface CreateWebhookRequest {
  ownerKind: WebhookOwnerKind;
  ownerId: string;
  url: string;
  scope: WebhookScope;
  note: string;
  /**
   * See Webhook.include_details. A client sets this only after the
   * person has been shown what it means and has accepted it.
   */
  includeDetails: boolean;
}

export interface UpdateWebhookRequest {
  id: WebhookID;
  url?: string;
  scope?: WebhookScope;
  note?: string;
  /**
   * Switching a webhook back on also clears its failure count: an owner
   * who has fixed an endpoint is telling the server to start over.
   */
  active?: boolean;
  includeDetails?: boolean;
}

export interface DeleteWebhookRequest {
  id: WebhookID;
}

export interface ListWebhooksRequest {
  ownerKind: WebhookOwnerKind;
  ownerId: string;
}

export interface WebhookList {
  webhooks: Webhook[];
  /**
   * How many this level may have. A client shows the count against the
   * limit rather than discovering it by being refused.
   */
  limit: number;
}

export function validateBeginLoginRequest(value: BeginLoginRequest): string[] {
  const errors: string[] = [];
  if (value.domain.length < 1 || value.domain.length > 253) errors.push("domain: length must be between 1 and 253");
  return errors;
}

const devLoginRequestHandleRe = new RegExp("^[a-z0-9]+(-[a-z0-9]+)*$");
export function validateDevLoginRequest(value: DevLoginRequest): string[] {
  const errors: string[] = [];
  if (value.handle.length < 1 || value.handle.length > 64) errors.push("handle: length must be between 1 and 64");
  if (!devLoginRequestHandleRe.test(value.handle)) errors.push("handle: must match the required pattern");
  if (value.domain.length < 1 || value.domain.length > 253) errors.push("domain: length must be between 1 and 253");
  return errors;
}

export function validateGreeting(value: Greeting): string[] {
  const errors: string[] = [];
  if (value.message.length < 1 || value.message.length > 280) errors.push("message: length must be between 1 and 280");
  return errors;
}

export function validateCreateGreetingRequest(value: CreateGreetingRequest): string[] {
  const errors: string[] = [];
  if (value.message.length < 1 || value.message.length > 280) errors.push("message: length must be between 1 and 280");
  return errors;
}

export function validateOrganization(value: Organization): string[] {
  const errors: string[] = [];
  if (value.name.length < 1 || value.name.length > 120) errors.push("name: length must be between 1 and 120");
  if (value.blurb.length < 0 || value.blurb.length > 4000) errors.push("blurb: length must be between 0 and 4000");
  if (value.description.length < 0 || value.description.length > 10000) errors.push("description: length must be between 0 and 10000");
  return errors;
}

export function validateCreateOrganizationRequest(value: CreateOrganizationRequest): string[] {
  const errors: string[] = [];
  if (value.name.length < 1 || value.name.length > 120) errors.push("name: length must be between 1 and 120");
  if (value.blurb.length < 0 || value.blurb.length > 4000) errors.push("blurb: length must be between 0 and 4000");
  if (value.description.length < 0 || value.description.length > 10000) errors.push("description: length must be between 0 and 10000");
  return errors;
}

export function validateUpdateOrganizationRequest(value: UpdateOrganizationRequest): string[] {
  const errors: string[] = [];
  if (value.name !== undefined) {
    if (value.name.length < 1 || value.name.length > 120) errors.push("name: length must be between 1 and 120");
  }
  if (value.blurb !== undefined) {
    if (value.blurb.length < 0 || value.blurb.length > 4000) errors.push("blurb: length must be between 0 and 4000");
  }
  if (value.description !== undefined) {
    if (value.description.length < 0 || value.description.length > 10000) errors.push("description: length must be between 0 and 10000");
  }
  return errors;
}

export function validateListOrganizationsRequest(value: ListOrganizationsRequest): string[] {
  const errors: string[] = [];
  if (value.query !== undefined) {
    if (value.query.length < 0 || value.query.length > 120) errors.push("query: length must be between 0 and 120");
  }
  return errors;
}

export function validateGathering(value: Gathering): string[] {
  const errors: string[] = [];
  if (value.name.length < 1 || value.name.length > 120) errors.push("name: length must be between 1 and 120");
  if (value.blurb.length < 0 || value.blurb.length > 4000) errors.push("blurb: length must be between 0 and 4000");
  if (value.description.length < 0 || value.description.length > 10000) errors.push("description: length must be between 0 and 10000");
  return errors;
}

export function validateCreateGatheringRequest(value: CreateGatheringRequest): string[] {
  const errors: string[] = [];
  if (value.name.length < 1 || value.name.length > 120) errors.push("name: length must be between 1 and 120");
  if (value.blurb.length < 0 || value.blurb.length > 4000) errors.push("blurb: length must be between 0 and 4000");
  if (value.description.length < 0 || value.description.length > 10000) errors.push("description: length must be between 0 and 10000");
  return errors;
}

export function validateUpdateGatheringRequest(value: UpdateGatheringRequest): string[] {
  const errors: string[] = [];
  if (value.name !== undefined) {
    if (value.name.length < 1 || value.name.length > 120) errors.push("name: length must be between 1 and 120");
  }
  if (value.blurb !== undefined) {
    if (value.blurb.length < 0 || value.blurb.length > 4000) errors.push("blurb: length must be between 0 and 4000");
  }
  if (value.description !== undefined) {
    if (value.description.length < 0 || value.description.length > 10000) errors.push("description: length must be between 0 and 10000");
  }
  return errors;
}

export function validateGatheringOffer(value: GatheringOffer): string[] {
  const errors: string[] = [];
  if (value.note.length < 0 || value.note.length > 500) errors.push("note: length must be between 0 and 500");
  return errors;
}

export function validateOfferGatheringRequest(value: OfferGatheringRequest): string[] {
  const errors: string[] = [];
  if (value.note.length < 0 || value.note.length > 500) errors.push("note: length must be between 0 and 500");
  return errors;
}

export function validateLocation(value: Location): string[] {
  const errors: string[] = [];
  if (value.name.length < 0 || value.name.length > 200) errors.push("name: length must be between 0 and 200");
  if (value.address.length < 0 || value.address.length > 300) errors.push("address: length must be between 0 and 300");
  if (value.locality.length < 0 || value.locality.length > 120) errors.push("locality: length must be between 0 and 120");
  if (value.region.length < 0 || value.region.length > 120) errors.push("region: length must be between 0 and 120");
  if (value.postalCode.length < 0 || value.postalCode.length > 32) errors.push("postalCode: length must be between 0 and 32");
  if (value.country.length < 0 || value.country.length > 2) errors.push("country: length must be between 0 and 2");
  return errors;
}

export function validateEvent(value: Event): string[] {
  const errors: string[] = [];
  if (value.title.length < 1 || value.title.length > 200) errors.push("title: length must be between 1 and 200");
  if (value.description !== undefined) {
    if (value.description.length < 0 || value.description.length > 10000) errors.push("description: length must be between 0 and 10000");
  }
  if (value.onlineUrl !== undefined) {
    if (value.onlineUrl.length < 0 || value.onlineUrl.length > 2000) errors.push("onlineUrl: length must be between 0 and 2000");
  }
  if (value.timezone.length < 1 || value.timezone.length > 64) errors.push("timezone: length must be between 1 and 64");
  return errors;
}

const eventSeriesStartTimeRe = new RegExp("^([01][0-9]|2[0-3]):[0-5][0-9]$");
export function validateEventSeries(value: EventSeries): string[] {
  const errors: string[] = [];
  if (value.title.length < 1 || value.title.length > 200) errors.push("title: length must be between 1 and 200");
  if (value.description.length < 0 || value.description.length > 10000) errors.push("description: length must be between 0 and 10000");
  if (value.onlineUrl !== undefined) {
    if (value.onlineUrl.length < 0 || value.onlineUrl.length > 2000) errors.push("onlineUrl: length must be between 0 and 2000");
  }
  if (value.startTime.length < 5 || value.startTime.length > 5) errors.push("startTime: length must be between 5 and 5");
  if (!eventSeriesStartTimeRe.test(value.startTime)) errors.push("startTime: must match the required pattern");
  if (value.timezone.length < 1 || value.timezone.length > 64) errors.push("timezone: length must be between 1 and 64");
  return errors;
}

export function validateCreateEventRequest(value: CreateEventRequest): string[] {
  const errors: string[] = [];
  if (value.title.length < 1 || value.title.length > 200) errors.push("title: length must be between 1 and 200");
  if (value.description.length < 0 || value.description.length > 10000) errors.push("description: length must be between 0 and 10000");
  if (value.onlineUrl !== undefined) {
    if (value.onlineUrl.length < 0 || value.onlineUrl.length > 2000) errors.push("onlineUrl: length must be between 0 and 2000");
  }
  if (value.timezone.length < 1 || value.timezone.length > 64) errors.push("timezone: length must be between 1 and 64");
  return errors;
}

export function validateUpdateEventRequest(value: UpdateEventRequest): string[] {
  const errors: string[] = [];
  if (value.title !== undefined) {
    if (value.title.length < 1 || value.title.length > 200) errors.push("title: length must be between 1 and 200");
  }
  if (value.description !== undefined) {
    if (value.description.length < 0 || value.description.length > 10000) errors.push("description: length must be between 0 and 10000");
  }
  if (value.onlineUrl !== undefined) {
    if (value.onlineUrl.length < 0 || value.onlineUrl.length > 2000) errors.push("onlineUrl: length must be between 0 and 2000");
  }
  if (value.timezone !== undefined) {
    if (value.timezone.length < 1 || value.timezone.length > 64) errors.push("timezone: length must be between 1 and 64");
  }
  return errors;
}

const createEventSeriesRequestStartTimeRe = new RegExp("^([01][0-9]|2[0-3]):[0-5][0-9]$");
export function validateCreateEventSeriesRequest(value: CreateEventSeriesRequest): string[] {
  const errors: string[] = [];
  if (value.title.length < 1 || value.title.length > 200) errors.push("title: length must be between 1 and 200");
  if (value.description.length < 0 || value.description.length > 10000) errors.push("description: length must be between 0 and 10000");
  if (value.onlineUrl !== undefined) {
    if (value.onlineUrl.length < 0 || value.onlineUrl.length > 2000) errors.push("onlineUrl: length must be between 0 and 2000");
  }
  if (value.startTime.length < 5 || value.startTime.length > 5) errors.push("startTime: length must be between 5 and 5");
  if (!createEventSeriesRequestStartTimeRe.test(value.startTime)) errors.push("startTime: must match the required pattern");
  if (value.timezone.length < 1 || value.timezone.length > 64) errors.push("timezone: length must be between 1 and 64");
  return errors;
}

const updateEventSeriesRequestStartTimeRe = new RegExp("^([01][0-9]|2[0-3]):[0-5][0-9]$");
export function validateUpdateEventSeriesRequest(value: UpdateEventSeriesRequest): string[] {
  const errors: string[] = [];
  if (value.title !== undefined) {
    if (value.title.length < 1 || value.title.length > 200) errors.push("title: length must be between 1 and 200");
  }
  if (value.description !== undefined) {
    if (value.description.length < 0 || value.description.length > 10000) errors.push("description: length must be between 0 and 10000");
  }
  if (value.onlineUrl !== undefined) {
    if (value.onlineUrl.length < 0 || value.onlineUrl.length > 2000) errors.push("onlineUrl: length must be between 0 and 2000");
  }
  if (value.startTime !== undefined) {
    if (value.startTime.length < 5 || value.startTime.length > 5) errors.push("startTime: length must be between 5 and 5");
    if (!updateEventSeriesRequestStartTimeRe.test(value.startTime)) errors.push("startTime: must match the required pattern");
  }
  if (value.timezone !== undefined) {
    if (value.timezone.length < 1 || value.timezone.length > 64) errors.push("timezone: length must be between 1 and 64");
  }
  return errors;
}

export function validateLocationFilter(value: LocationFilter): string[] {
  const errors: string[] = [];
  if (value.locality !== undefined) {
    if (value.locality.length < 0 || value.locality.length > 120) errors.push("locality: length must be between 0 and 120");
  }
  if (value.region !== undefined) {
    if (value.region.length < 0 || value.region.length > 120) errors.push("region: length must be between 0 and 120");
  }
  if (value.country !== undefined) {
    if (value.country.length < 0 || value.country.length > 2) errors.push("country: length must be between 0 and 2");
  }
  return errors;
}

export function validateSearchRequest(value: SearchRequest): string[] {
  const errors: string[] = [];
  if (value.query !== undefined) {
    if (value.query.length < 0 || value.query.length > 200) errors.push("query: length must be between 0 and 200");
  }
  return errors;
}

export function validateFindUserRequest(value: FindUserRequest): string[] {
  const errors: string[] = [];
  if (value.handle.length < 1 || value.handle.length > 64) errors.push("handle: length must be between 1 and 64");
  if (value.domain.length < 1 || value.domain.length > 253) errors.push("domain: length must be between 1 and 253");
  return errors;
}

export function validateSearchUsersRequest(value: SearchUsersRequest): string[] {
  const errors: string[] = [];
  if (value.query.length < 1 || value.query.length > 64) errors.push("query: length must be between 1 and 64");
  return errors;
}

export function validatePeer(value: Peer): string[] {
  const errors: string[] = [];
  if (value.baseUrl.length < 0 || value.baseUrl.length > 2000) errors.push("baseUrl: length must be between 0 and 2000");
  if (value.note.length < 0 || value.note.length > 1000) errors.push("note: length must be between 0 and 1000");
  return errors;
}

export function validateAddPeerRequest(value: AddPeerRequest): string[] {
  const errors: string[] = [];
  if (value.address.length < 3 || value.address.length > 317) errors.push("address: length must be between 3 and 317");
  if (value.baseUrl.length < 1 || value.baseUrl.length > 2000) errors.push("baseUrl: length must be between 1 and 2000");
  if (value.note.length < 0 || value.note.length > 1000) errors.push("note: length must be between 0 and 1000");
  return errors;
}

export function validateFederatedEvent(value: FederatedEvent): string[] {
  const errors: string[] = [];
  if (value.canonicalUrl.length < 1 || value.canonicalUrl.length > 2000) errors.push("canonicalUrl: length must be between 1 and 2000");
  if (value.title.length < 1 || value.title.length > 200) errors.push("title: length must be between 1 and 200");
  if (value.timezone.length < 1 || value.timezone.length > 64) errors.push("timezone: length must be between 1 and 64");
  if (value.gatheringName.length < 0 || value.gatheringName.length > 120) errors.push("gatheringName: length must be between 0 and 120");
  if (value.organizationName.length < 0 || value.organizationName.length > 120) errors.push("organizationName: length must be between 0 and 120");
  return errors;
}

export function validateEventBatch(value: EventBatch): string[] {
  const errors: string[] = [];
  if (value.batchId.length < 1 || value.batchId.length > 64) errors.push("batchId: length must be between 1 and 64");
  return errors;
}

export function validateSignedDelivery(value: SignedDelivery): string[] {
  const errors: string[] = [];
  if (value.senderAddress.length < 3 || value.senderAddress.length > 317) errors.push("senderAddress: length must be between 3 and 317");
  if (value.algorithm.length < 1 || value.algorithm.length > 64) errors.push("algorithm: length must be between 1 and 64");
  if (value.keyId.length < 1 || value.keyId.length > 128) errors.push("keyId: length must be between 1 and 128");
  if (value.signature.length < 1 || value.signature.length > 4000) errors.push("signature: length must be between 1 and 4000");
  return errors;
}

export function validatePeeringBody(value: PeeringBody): string[] {
  const errors: string[] = [];
  if (value.baseUrl.length < 1 || value.baseUrl.length > 2000) errors.push("baseUrl: length must be between 1 and 2000");
  if (value.note.length < 0 || value.note.length > 1000) errors.push("note: length must be between 0 and 1000");
  return errors;
}

export function validateSignedPeeringRequest(value: SignedPeeringRequest): string[] {
  const errors: string[] = [];
  if (value.senderAddress.length < 3 || value.senderAddress.length > 317) errors.push("senderAddress: length must be between 3 and 317");
  if (value.algorithm.length < 1 || value.algorithm.length > 64) errors.push("algorithm: length must be between 1 and 64");
  if (value.keyId.length < 1 || value.keyId.length > 128) errors.push("keyId: length must be between 1 and 128");
  if (value.subjectUserId.length < 1 || value.subjectUserId.length > 128) errors.push("subjectUserId: length must be between 1 and 128");
  if (value.subjectDomain.length < 1 || value.subjectDomain.length > 253) errors.push("subjectDomain: length must be between 1 and 253");
  if (value.applicationId.length < 1 || value.applicationId.length > 128) errors.push("applicationId: length must be between 1 and 128");
  if (value.instanceId.length < 1 || value.instanceId.length > 128) errors.push("instanceId: length must be between 1 and 128");
  if (value.signature.length < 1 || value.signature.length > 4000) errors.push("signature: length must be between 1 and 4000");
  return errors;
}

export function validateListRemoteEventsRequest(value: ListRemoteEventsRequest): string[] {
  const errors: string[] = [];
  if (value.query !== undefined) {
    if (value.query.length < 0 || value.query.length > 200) errors.push("query: length must be between 0 and 200");
  }
  return errors;
}

export function validateWebhook(value: Webhook): string[] {
  const errors: string[] = [];
  if (value.url.length < 1 || value.url.length > 2000) errors.push("url: length must be between 1 and 2000");
  if (value.note.length < 0 || value.note.length > 200) errors.push("note: length must be between 0 and 200");
  return errors;
}

export function validateCreateWebhookRequest(value: CreateWebhookRequest): string[] {
  const errors: string[] = [];
  if (value.url.length < 1 || value.url.length > 2000) errors.push("url: length must be between 1 and 2000");
  if (value.note.length < 0 || value.note.length > 200) errors.push("note: length must be between 0 and 200");
  return errors;
}

export function validateUpdateWebhookRequest(value: UpdateWebhookRequest): string[] {
  const errors: string[] = [];
  if (value.url !== undefined) {
    if (value.url.length < 1 || value.url.length > 2000) errors.push("url: length must be between 1 and 2000");
  }
  if (value.note !== undefined) {
    if (value.note.length < 0 || value.note.length > 200) errors.push("note: length must be between 0 and 200");
  }
  return errors;
}

