// Package csil contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package csil

import (
	"time"
)

// UserID is a type alias
type UserID string

// GreetingID is a type alias
type GreetingID string

// OrganizationID is a type alias
type OrganizationID string

// GatheringID is a type alias
type GatheringID string

// EventID is a type alias
type EventID string

// EventSeriesID is a type alias
type EventSeriesID string

// Empty represents a structured data type
type Empty struct {
}

// ViewerContext represents a structured data type
type ViewerContext struct {
	IsAdmin          bool `json:"is_admin" yaml:"is_admin"`
	IsOwner          bool `json:"is_owner" yaml:"is_owner"`
	IsOrganizer      bool `json:"is_organizer" yaml:"is_organizer"`
	IsPresenter      bool `json:"is_presenter" yaml:"is_presenter"`
	IsMember         bool `json:"is_member" yaml:"is_member"`
	HasJoined        bool `json:"has_joined" yaml:"has_joined"`
	CanEdit          bool `json:"can_edit" yaml:"can_edit"`
	CanDelete        bool `json:"can_delete" yaml:"can_delete"`
	CanManageMembers bool `json:"can_manage_members" yaml:"can_manage_members"`
}

// Page represents a structured data type
type Page struct {
	Limit  *uint64 `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset *uint64 `json:"offset,omitempty" yaml:"offset,omitempty"`
}

// PublishSetting is a type alias
type PublishSetting string

// PublishSource is a type alias
type PublishSource string

// PublishDecision represents a structured data type
type PublishDecision struct {
	Publishing  bool          `json:"publishing" yaml:"publishing"`
	Source      PublishSource `json:"source" yaml:"source"`
	CanOverride bool          `json:"can_override" yaml:"can_override"`
}

// Origin represents a structured data type
type Origin struct {
	Domain      string  `json:"domain" yaml:"domain"`
	IsExternal  bool    `json:"is_external" yaml:"is_external"`
	PeerAddress *string `json:"peer_address,omitempty" yaml:"peer_address,omitempty"`
}

// ServiceError represents a structured data type
type ServiceError struct {
	Code         uint64  `json:"code" yaml:"code"`
	Message      string  `json:"message" yaml:"message"`
	Field        *string `json:"field,omitempty" yaml:"field,omitempty"`
	ResourceType *string `json:"resource_type,omitempty" yaml:"resource_type,omitempty"`
}

// UserKind is a type alias
type UserKind string

// BeginLoginRequest represents a structured data type
type BeginLoginRequest struct {
	Domain string `json:"domain" yaml:"domain"`
}

// BeginLoginResponse represents a structured data type
type BeginLoginResponse struct {
	RedirectUrl string `json:"redirect_url" yaml:"redirect_url"`
}

// UserProfile represents a structured data type
type UserProfile struct {
	Id             UserID    `json:"id" yaml:"id"`
	LinkkeysDomain string    `json:"linkkeys_domain" yaml:"linkkeys_domain"`
	Handle         string    `json:"handle" yaml:"handle"`
	DisplayName    string    `json:"display_name" yaml:"display_name"`
	Kind           UserKind  `json:"kind" yaml:"kind"`
	CreatedAt      time.Time `json:"created_at" yaml:"created_at"`
}

// DevLoginRequest represents a structured data type
type DevLoginRequest struct {
	Handle string `json:"handle" yaml:"handle"`
	Domain string `json:"domain" yaml:"domain"`
}

// Greeting represents a structured data type
type Greeting struct {
	Id           GreetingID `json:"id" yaml:"id"`
	AuthorId     *UserID    `json:"author_id,omitempty" yaml:"author_id,omitempty"`
	AuthorHandle *string    `json:"author_handle,omitempty" yaml:"author_handle,omitempty"`
	Message      string     `json:"message" yaml:"message"`
	CreatedAt    time.Time  `json:"created_at" yaml:"created_at"`
}

// GreetingList represents a structured data type
type GreetingList struct {
	Greetings []Greeting `json:"greetings" yaml:"greetings"`
}

// CreateGreetingRequest represents a structured data type
type CreateGreetingRequest struct {
	Message string `json:"message" yaml:"message"`
}

// GetGreetingRequest represents a structured data type
type GetGreetingRequest struct {
	Id GreetingID `json:"id" yaml:"id"`
}

// OrganizationRole is a type alias
type OrganizationRole string

// Organization represents a structured data type
type Organization struct {
	Id            OrganizationID `json:"id" yaml:"id"`
	Slug          string         `json:"slug" yaml:"slug"`
	OriginDomain  string         `json:"origin_domain" yaml:"origin_domain"`
	Name          string         `json:"name" yaml:"name"`
	Blurb         string         `json:"blurb" yaml:"blurb"`
	Description   string         `json:"description" yaml:"description"`
	MemberCount   uint64         `json:"member_count" yaml:"member_count"`
	OwnerCount    uint64         `json:"owner_count" yaml:"owner_count"`
	PublishEvents PublishSetting `json:"publish_events" yaml:"publish_events"`
	Origin        Origin         `json:"origin" yaml:"origin"`
	Viewer        ViewerContext  `json:"viewer" yaml:"viewer"`
	CreatedAt     time.Time      `json:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at" yaml:"updated_at"`
}

// OrganizationMember represents a structured data type
type OrganizationMember struct {
	UserId         UserID           `json:"user_id" yaml:"user_id"`
	Handle         string           `json:"handle" yaml:"handle"`
	LinkkeysDomain string           `json:"linkkeys_domain" yaml:"linkkeys_domain"`
	DisplayName    string           `json:"display_name" yaml:"display_name"`
	Role           OrganizationRole `json:"role" yaml:"role"`
	JoinedAt       time.Time        `json:"joined_at" yaml:"joined_at"`
}

// CreateOrganizationRequest represents a structured data type
type CreateOrganizationRequest struct {
	Name        string `json:"name" yaml:"name"`
	Blurb       string `json:"blurb" yaml:"blurb"`
	Description string `json:"description" yaml:"description"`
}

// UpdateOrganizationRequest represents a structured data type
type UpdateOrganizationRequest struct {
	Id            OrganizationID  `json:"id" yaml:"id"`
	Name          *string         `json:"name,omitempty" yaml:"name,omitempty"`
	Blurb         *string         `json:"blurb,omitempty" yaml:"blurb,omitempty"`
	Description   *string         `json:"description,omitempty" yaml:"description,omitempty"`
	PublishEvents *PublishSetting `json:"publish_events,omitempty" yaml:"publish_events,omitempty"`
}

// GetOrganizationRequest represents a structured data type
type GetOrganizationRequest struct {
	Id OrganizationID `json:"id" yaml:"id"`
}

// DeleteOrganizationRequest represents a structured data type
type DeleteOrganizationRequest struct {
	Id OrganizationID `json:"id" yaml:"id"`
}

// ListOrganizationsRequest represents a structured data type
type ListOrganizationsRequest struct {
	Mine *bool `json:"mine,omitempty" yaml:"mine,omitempty"`
	Page *Page `json:"page,omitempty" yaml:"page,omitempty"`
}

// OrganizationList represents a structured data type
type OrganizationList struct {
	Organizations []Organization `json:"organizations" yaml:"organizations"`
	Total         uint64         `json:"total" yaml:"total"`
}

// OrganizationMemberList represents a structured data type
type OrganizationMemberList struct {
	OrganizationId OrganizationID       `json:"organization_id" yaml:"organization_id"`
	Members        []OrganizationMember `json:"members" yaml:"members"`
	Total          uint64               `json:"total" yaml:"total"`
}

// ListOrganizationMembersRequest represents a structured data type
type ListOrganizationMembersRequest struct {
	OrganizationId OrganizationID `json:"organization_id" yaml:"organization_id"`
	Page           *Page          `json:"page,omitempty" yaml:"page,omitempty"`
}

// SetOrganizationMemberRequest represents a structured data type
type SetOrganizationMemberRequest struct {
	OrganizationId OrganizationID   `json:"organization_id" yaml:"organization_id"`
	UserId         UserID           `json:"user_id" yaml:"user_id"`
	Role           OrganizationRole `json:"role" yaml:"role"`
}

// RemoveOrganizationMemberRequest represents a structured data type
type RemoveOrganizationMemberRequest struct {
	OrganizationId OrganizationID `json:"organization_id" yaml:"organization_id"`
	UserId         UserID         `json:"user_id" yaml:"user_id"`
}

// OwnerKind is a type alias
type OwnerKind string

// GatheringRole is a type alias
type GatheringRole string

// OwnerRef represents a structured data type
type OwnerRef struct {
	Kind         OwnerKind `json:"kind" yaml:"kind"`
	Id           string    `json:"id" yaml:"id"`
	DisplayName  string    `json:"display_name" yaml:"display_name"`
	Handle       string    `json:"handle" yaml:"handle"`
	OriginDomain string    `json:"origin_domain" yaml:"origin_domain"`
}

// OwnerRefInput represents a structured data type
type OwnerRefInput struct {
	Kind OwnerKind `json:"kind" yaml:"kind"`
	Id   string    `json:"id" yaml:"id"`
}

// Gathering represents a structured data type
type Gathering struct {
	Id            GatheringID     `json:"id" yaml:"id"`
	Slug          string          `json:"slug" yaml:"slug"`
	OriginDomain  string          `json:"origin_domain" yaml:"origin_domain"`
	Name          string          `json:"name" yaml:"name"`
	Blurb         string          `json:"blurb" yaml:"blurb"`
	Description   string          `json:"description" yaml:"description"`
	Owners        []OwnerRef      `json:"owners" yaml:"owners"`
	MemberCount   uint64          `json:"member_count" yaml:"member_count"`
	EventCount    uint64          `json:"event_count" yaml:"event_count"`
	NextEventAt   *time.Time      `json:"next_event_at,omitempty" yaml:"next_event_at,omitempty"`
	PublishEvents PublishSetting  `json:"publish_events" yaml:"publish_events"`
	Publish       PublishDecision `json:"publish" yaml:"publish"`
	Origin        Origin          `json:"origin" yaml:"origin"`
	Viewer        ViewerContext   `json:"viewer" yaml:"viewer"`
	CreatedAt     time.Time       `json:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at" yaml:"updated_at"`
}

// GatheringMember represents a structured data type
type GatheringMember struct {
	UserId         UserID    `json:"user_id" yaml:"user_id"`
	Handle         string    `json:"handle" yaml:"handle"`
	LinkkeysDomain string    `json:"linkkeys_domain" yaml:"linkkeys_domain"`
	DisplayName    string    `json:"display_name" yaml:"display_name"`
	JoinedAt       time.Time `json:"joined_at" yaml:"joined_at"`
}

// CreateGatheringRequest represents a structured data type
type CreateGatheringRequest struct {
	Name        string         `json:"name" yaml:"name"`
	Blurb       string         `json:"blurb" yaml:"blurb"`
	Description string         `json:"description" yaml:"description"`
	Owner       *OwnerRefInput `json:"owner,omitempty" yaml:"owner,omitempty"`
}

// UpdateGatheringRequest represents a structured data type
type UpdateGatheringRequest struct {
	Id            GatheringID     `json:"id" yaml:"id"`
	Name          *string         `json:"name,omitempty" yaml:"name,omitempty"`
	Blurb         *string         `json:"blurb,omitempty" yaml:"blurb,omitempty"`
	Description   *string         `json:"description,omitempty" yaml:"description,omitempty"`
	PublishEvents *PublishSetting `json:"publish_events,omitempty" yaml:"publish_events,omitempty"`
}

// GetGatheringRequest represents a structured data type
type GetGatheringRequest struct {
	Id GatheringID `json:"id" yaml:"id"`
}

// DeleteGatheringRequest represents a structured data type
type DeleteGatheringRequest struct {
	Id GatheringID `json:"id" yaml:"id"`
}

// ListGatheringsRequest represents a structured data type
type ListGatheringsRequest struct {
	Mine                *bool           `json:"mine,omitempty" yaml:"mine,omitempty"`
	OwnedByOrganization *OrganizationID `json:"owned_by_organization,omitempty" yaml:"owned_by_organization,omitempty"`
	Page                *Page           `json:"page,omitempty" yaml:"page,omitempty"`
}

// GatheringList represents a structured data type
type GatheringList struct {
	Gatherings []Gathering `json:"gatherings" yaml:"gatherings"`
	Total      uint64      `json:"total" yaml:"total"`
}

// ListGatheringMembersRequest represents a structured data type
type ListGatheringMembersRequest struct {
	GatheringId GatheringID `json:"gathering_id" yaml:"gathering_id"`
	Page        *Page       `json:"page,omitempty" yaml:"page,omitempty"`
}

// GatheringMemberList represents a structured data type
type GatheringMemberList struct {
	GatheringId GatheringID       `json:"gathering_id" yaml:"gathering_id"`
	Members     []GatheringMember `json:"members" yaml:"members"`
	Total       uint64            `json:"total" yaml:"total"`
}

// JoinGatheringRequest represents a structured data type
type JoinGatheringRequest struct {
	GatheringId GatheringID `json:"gathering_id" yaml:"gathering_id"`
}

// LeaveGatheringRequest represents a structured data type
type LeaveGatheringRequest struct {
	GatheringId GatheringID `json:"gathering_id" yaml:"gathering_id"`
}

// AddGatheringOwnerRequest represents a structured data type
type AddGatheringOwnerRequest struct {
	GatheringId GatheringID   `json:"gathering_id" yaml:"gathering_id"`
	Owner       OwnerRefInput `json:"owner" yaml:"owner"`
}

// RemoveGatheringOwnerRequest represents a structured data type
type RemoveGatheringOwnerRequest struct {
	GatheringId GatheringID   `json:"gathering_id" yaml:"gathering_id"`
	Owner       OwnerRefInput `json:"owner" yaml:"owner"`
}

// Weekday is a type alias
type Weekday string

// RecurrenceFreq is a type alias
type RecurrenceFreq string

// RecurrenceRule represents a structured data type
type RecurrenceRule struct {
	Freq       RecurrenceFreq `json:"freq" yaml:"freq"`
	Interval   uint64         `json:"interval" yaml:"interval"`
	Weekday    *Weekday       `json:"weekday,omitempty" yaml:"weekday,omitempty"`
	Ordinal    *int64         `json:"ordinal,omitempty" yaml:"ordinal,omitempty"`
	DayOfMonth *uint64        `json:"day_of_month,omitempty" yaml:"day_of_month,omitempty"`
}

// Location represents a structured data type
type Location struct {
	Name       string   `json:"name" yaml:"name"`
	Address    string   `json:"address" yaml:"address"`
	Locality   string   `json:"locality" yaml:"locality"`
	Region     string   `json:"region" yaml:"region"`
	PostalCode string   `json:"postal_code" yaml:"postal_code"`
	Country    string   `json:"country" yaml:"country"`
	Latitude   *float64 `json:"latitude,omitempty" yaml:"latitude,omitempty"`
	Longitude  *float64 `json:"longitude,omitempty" yaml:"longitude,omitempty"`
}

// Event represents a structured data type
type Event struct {
	Id              EventID        `json:"id" yaml:"id"`
	GatheringId     GatheringID    `json:"gathering_id" yaml:"gathering_id"`
	SeriesId        *EventSeriesID `json:"series_id,omitempty" yaml:"series_id,omitempty"`
	Title           string         `json:"title" yaml:"title"`
	Description     *string        `json:"description,omitempty" yaml:"description,omitempty"`
	IsOnline        bool           `json:"is_online" yaml:"is_online"`
	IsInPerson      bool           `json:"is_in_person" yaml:"is_in_person"`
	OnlineUrl       *string        `json:"online_url,omitempty" yaml:"online_url,omitempty"`
	Location        *Location      `json:"location,omitempty" yaml:"location,omitempty"`
	StartsAt        time.Time      `json:"starts_at" yaml:"starts_at"`
	EndsAt          time.Time      `json:"ends_at" yaml:"ends_at"`
	Timezone        string         `json:"timezone" yaml:"timezone"`
	Locked          bool           `json:"locked" yaml:"locked"`
	AttendeeCount   uint64         `json:"attendee_count" yaml:"attendee_count"`
	ViewerAttending bool           `json:"viewer_attending" yaml:"viewer_attending"`
	Origin          Origin         `json:"origin" yaml:"origin"`
	Viewer          ViewerContext  `json:"viewer" yaml:"viewer"`
	CreatedAt       time.Time      `json:"created_at" yaml:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at" yaml:"updated_at"`
}

// EventSeries represents a structured data type
type EventSeries struct {
	Id               EventSeriesID  `json:"id" yaml:"id"`
	GatheringId      GatheringID    `json:"gathering_id" yaml:"gathering_id"`
	Title            string         `json:"title" yaml:"title"`
	Description      string         `json:"description" yaml:"description"`
	IsOnline         bool           `json:"is_online" yaml:"is_online"`
	IsInPerson       bool           `json:"is_in_person" yaml:"is_in_person"`
	OnlineUrl        *string        `json:"online_url,omitempty" yaml:"online_url,omitempty"`
	Location         *Location      `json:"location,omitempty" yaml:"location,omitempty"`
	Recurrence       RecurrenceRule `json:"recurrence" yaml:"recurrence"`
	StartsOn         time.Time      `json:"starts_on" yaml:"starts_on"`
	EndsOn           *time.Time     `json:"ends_on,omitempty" yaml:"ends_on,omitempty"`
	StartTime        string         `json:"start_time" yaml:"start_time"`
	DurationMinutes  uint64         `json:"duration_minutes" yaml:"duration_minutes"`
	Timezone         string         `json:"timezone" yaml:"timezone"`
	OccurrenceCount  uint64         `json:"occurrence_count" yaml:"occurrence_count"`
	NextOccurrenceAt *time.Time     `json:"next_occurrence_at,omitempty" yaml:"next_occurrence_at,omitempty"`
	Origin           Origin         `json:"origin" yaml:"origin"`
	Viewer           ViewerContext  `json:"viewer" yaml:"viewer"`
	CreatedAt        time.Time      `json:"created_at" yaml:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at" yaml:"updated_at"`
}

// EventRole is a type alias
type EventRole string

// EventRoleAssignment represents a structured data type
type EventRoleAssignment struct {
	EventId        *EventID       `json:"event_id,omitempty" yaml:"event_id,omitempty"`
	SeriesId       *EventSeriesID `json:"series_id,omitempty" yaml:"series_id,omitempty"`
	UserId         UserID         `json:"user_id" yaml:"user_id"`
	Handle         string         `json:"handle" yaml:"handle"`
	LinkkeysDomain string         `json:"linkkeys_domain" yaml:"linkkeys_domain"`
	DisplayName    string         `json:"display_name" yaml:"display_name"`
	Role           EventRole      `json:"role" yaml:"role"`
	AssignedAt     time.Time      `json:"assigned_at" yaml:"assigned_at"`
}

// Attendee represents a structured data type
type Attendee struct {
	UserId         UserID    `json:"user_id" yaml:"user_id"`
	Handle         string    `json:"handle" yaml:"handle"`
	LinkkeysDomain string    `json:"linkkeys_domain" yaml:"linkkeys_domain"`
	DisplayName    string    `json:"display_name" yaml:"display_name"`
	MarkedAt       time.Time `json:"marked_at" yaml:"marked_at"`
}

// CreateEventRequest represents a structured data type
type CreateEventRequest struct {
	GatheringId GatheringID `json:"gathering_id" yaml:"gathering_id"`
	Title       string      `json:"title" yaml:"title"`
	Description string      `json:"description" yaml:"description"`
	IsOnline    bool        `json:"is_online" yaml:"is_online"`
	IsInPerson  bool        `json:"is_in_person" yaml:"is_in_person"`
	OnlineUrl   *string     `json:"online_url,omitempty" yaml:"online_url,omitempty"`
	Location    *Location   `json:"location,omitempty" yaml:"location,omitempty"`
	StartsAt    time.Time   `json:"starts_at" yaml:"starts_at"`
	EndsAt      time.Time   `json:"ends_at" yaml:"ends_at"`
	Timezone    string      `json:"timezone" yaml:"timezone"`
}

// UpdateEventRequest represents a structured data type
type UpdateEventRequest struct {
	Id          EventID    `json:"id" yaml:"id"`
	Title       *string    `json:"title,omitempty" yaml:"title,omitempty"`
	Description *string    `json:"description,omitempty" yaml:"description,omitempty"`
	IsOnline    *bool      `json:"is_online,omitempty" yaml:"is_online,omitempty"`
	IsInPerson  *bool      `json:"is_in_person,omitempty" yaml:"is_in_person,omitempty"`
	OnlineUrl   *string    `json:"online_url,omitempty" yaml:"online_url,omitempty"`
	Location    *Location  `json:"location,omitempty" yaml:"location,omitempty"`
	StartsAt    *time.Time `json:"starts_at,omitempty" yaml:"starts_at,omitempty"`
	EndsAt      *time.Time `json:"ends_at,omitempty" yaml:"ends_at,omitempty"`
	Timezone    *string    `json:"timezone,omitempty" yaml:"timezone,omitempty"`
}

// GetEventRequest represents a structured data type
type GetEventRequest struct {
	Id EventID `json:"id" yaml:"id"`
}

// DeleteEventRequest represents a structured data type
type DeleteEventRequest struct {
	Id EventID `json:"id" yaml:"id"`
}

// ListEventsRequest represents a structured data type
type ListEventsRequest struct {
	GatheringId    *GatheringID `json:"gathering_id,omitempty" yaml:"gathering_id,omitempty"`
	StartsAfter    *time.Time   `json:"starts_after,omitempty" yaml:"starts_after,omitempty"`
	StartsBefore   *time.Time   `json:"starts_before,omitempty" yaml:"starts_before,omitempty"`
	AttendingOnly  *bool        `json:"attending_only,omitempty" yaml:"attending_only,omitempty"`
	IncludeStarted *bool        `json:"include_started,omitempty" yaml:"include_started,omitempty"`
	Page           *Page        `json:"page,omitempty" yaml:"page,omitempty"`
}

// EventList represents a structured data type
type EventList struct {
	Events []Event `json:"events" yaml:"events"`
	Total  uint64  `json:"total" yaml:"total"`
}

// CreateEventSeriesRequest represents a structured data type
type CreateEventSeriesRequest struct {
	GatheringId     GatheringID    `json:"gathering_id" yaml:"gathering_id"`
	Title           string         `json:"title" yaml:"title"`
	Description     string         `json:"description" yaml:"description"`
	IsOnline        bool           `json:"is_online" yaml:"is_online"`
	IsInPerson      bool           `json:"is_in_person" yaml:"is_in_person"`
	OnlineUrl       *string        `json:"online_url,omitempty" yaml:"online_url,omitempty"`
	Location        *Location      `json:"location,omitempty" yaml:"location,omitempty"`
	Recurrence      RecurrenceRule `json:"recurrence" yaml:"recurrence"`
	StartsOn        time.Time      `json:"starts_on" yaml:"starts_on"`
	EndsOn          *time.Time     `json:"ends_on,omitempty" yaml:"ends_on,omitempty"`
	StartTime       string         `json:"start_time" yaml:"start_time"`
	DurationMinutes uint64         `json:"duration_minutes" yaml:"duration_minutes"`
	Timezone        string         `json:"timezone" yaml:"timezone"`
}

// UpdateEventSeriesRequest represents a structured data type
type UpdateEventSeriesRequest struct {
	Id              EventSeriesID   `json:"id" yaml:"id"`
	Title           *string         `json:"title,omitempty" yaml:"title,omitempty"`
	Description     *string         `json:"description,omitempty" yaml:"description,omitempty"`
	IsOnline        *bool           `json:"is_online,omitempty" yaml:"is_online,omitempty"`
	IsInPerson      *bool           `json:"is_in_person,omitempty" yaml:"is_in_person,omitempty"`
	OnlineUrl       *string         `json:"online_url,omitempty" yaml:"online_url,omitempty"`
	Location        *Location       `json:"location,omitempty" yaml:"location,omitempty"`
	Recurrence      *RecurrenceRule `json:"recurrence,omitempty" yaml:"recurrence,omitempty"`
	StartsOn        *time.Time      `json:"starts_on,omitempty" yaml:"starts_on,omitempty"`
	EndsOn          *time.Time      `json:"ends_on,omitempty" yaml:"ends_on,omitempty"`
	StartTime       *string         `json:"start_time,omitempty" yaml:"start_time,omitempty"`
	DurationMinutes *uint64         `json:"duration_minutes,omitempty" yaml:"duration_minutes,omitempty"`
	Timezone        *string         `json:"timezone,omitempty" yaml:"timezone,omitempty"`
}

// GetEventSeriesRequest represents a structured data type
type GetEventSeriesRequest struct {
	Id EventSeriesID `json:"id" yaml:"id"`
}

// DeleteEventSeriesRequest represents a structured data type
type DeleteEventSeriesRequest struct {
	Id EventSeriesID `json:"id" yaml:"id"`
}

// ListEventSeriesRequest represents a structured data type
type ListEventSeriesRequest struct {
	GatheringId *GatheringID `json:"gathering_id,omitempty" yaml:"gathering_id,omitempty"`
	Page        *Page        `json:"page,omitempty" yaml:"page,omitempty"`
}

// EventSeriesList represents a structured data type
type EventSeriesList struct {
	Series []EventSeries `json:"series" yaml:"series"`
	Total  uint64        `json:"total" yaml:"total"`
}

// ExpandEventSeriesRequest represents a structured data type
type ExpandEventSeriesRequest struct {
	SeriesId EventSeriesID `json:"series_id" yaml:"series_id"`
	Through  *time.Time    `json:"through,omitempty" yaml:"through,omitempty"`
}

// AttendEventRequest represents a structured data type
type AttendEventRequest struct {
	EventId EventID `json:"event_id" yaml:"event_id"`
}

// UnattendEventRequest represents a structured data type
type UnattendEventRequest struct {
	EventId EventID `json:"event_id" yaml:"event_id"`
}

// ListAttendeesRequest represents a structured data type
type ListAttendeesRequest struct {
	EventId EventID `json:"event_id" yaml:"event_id"`
	Page    *Page   `json:"page,omitempty" yaml:"page,omitempty"`
}

// AttendeeList represents a structured data type
type AttendeeList struct {
	EventId   EventID    `json:"event_id" yaml:"event_id"`
	Attendees []Attendee `json:"attendees" yaml:"attendees"`
	Total     uint64     `json:"total" yaml:"total"`
}

// SetEventRoleRequest represents a structured data type
type SetEventRoleRequest struct {
	EventId  *EventID       `json:"event_id,omitempty" yaml:"event_id,omitempty"`
	SeriesId *EventSeriesID `json:"series_id,omitempty" yaml:"series_id,omitempty"`
	UserId   UserID         `json:"user_id" yaml:"user_id"`
	Role     EventRole      `json:"role" yaml:"role"`
}

// RemoveEventRoleRequest represents a structured data type
type RemoveEventRoleRequest struct {
	EventId  *EventID       `json:"event_id,omitempty" yaml:"event_id,omitempty"`
	SeriesId *EventSeriesID `json:"series_id,omitempty" yaml:"series_id,omitempty"`
	UserId   UserID         `json:"user_id" yaml:"user_id"`
	Role     EventRole      `json:"role" yaml:"role"`
}

// ListEventRolesRequest represents a structured data type
type ListEventRolesRequest struct {
	EventId  *EventID       `json:"event_id,omitempty" yaml:"event_id,omitempty"`
	SeriesId *EventSeriesID `json:"series_id,omitempty" yaml:"series_id,omitempty"`
}

// EventRoleList represents a structured data type
type EventRoleList struct {
	Roles []EventRoleAssignment `json:"roles" yaml:"roles"`
}

// SearchKind is a type alias
type SearchKind string

// GeoCircle represents a structured data type
type GeoCircle struct {
	Latitude  float64 `json:"latitude" yaml:"latitude"`
	Longitude float64 `json:"longitude" yaml:"longitude"`
	RadiusKm  float64 `json:"radius_km" yaml:"radius_km"`
}

// LocationFilter represents a structured data type
type LocationFilter struct {
	Locality *string    `json:"locality,omitempty" yaml:"locality,omitempty"`
	Region   *string    `json:"region,omitempty" yaml:"region,omitempty"`
	Country  *string    `json:"country,omitempty" yaml:"country,omitempty"`
	Near     *GeoCircle `json:"near,omitempty" yaml:"near,omitempty"`
}

// SearchRequest represents a structured data type
type SearchRequest struct {
	Query          *string         `json:"query,omitempty" yaml:"query,omitempty"`
	Kinds          []SearchKind    `json:"kinds,omitempty" yaml:"kinds,omitempty"`
	Location       *LocationFilter `json:"location,omitempty" yaml:"location,omitempty"`
	StartsAfter    *time.Time      `json:"starts_after,omitempty" yaml:"starts_after,omitempty"`
	StartsBefore   *time.Time      `json:"starts_before,omitempty" yaml:"starts_before,omitempty"`
	OnlineOnly     *bool           `json:"online_only,omitempty" yaml:"online_only,omitempty"`
	InPersonOnly   *bool           `json:"in_person_only,omitempty" yaml:"in_person_only,omitempty"`
	IncludeStarted *bool           `json:"include_started,omitempty" yaml:"include_started,omitempty"`
	Page           *Page           `json:"page,omitempty" yaml:"page,omitempty"`
}

// SearchResults represents a structured data type
type SearchResults struct {
	Organizations     []Organization `json:"organizations" yaml:"organizations"`
	Gatherings        []Gathering    `json:"gatherings" yaml:"gatherings"`
	Events            []Event        `json:"events" yaml:"events"`
	Series            []EventSeries  `json:"series" yaml:"series"`
	RemoteEvents      []RemoteEvent  `json:"remote_events" yaml:"remote_events"`
	OrganizationTotal uint64         `json:"organization_total" yaml:"organization_total"`
	GatheringTotal    uint64         `json:"gathering_total" yaml:"gathering_total"`
	EventTotal        uint64         `json:"event_total" yaml:"event_total"`
	SeriesTotal       uint64         `json:"series_total" yaml:"series_total"`
	RemoteEventTotal  uint64         `json:"remote_event_total" yaml:"remote_event_total"`
}

// AdminUser represents a structured data type
type AdminUser struct {
	UserId         UserID    `json:"user_id" yaml:"user_id"`
	Handle         string    `json:"handle" yaml:"handle"`
	LinkkeysDomain string    `json:"linkkeys_domain" yaml:"linkkeys_domain"`
	DisplayName    string    `json:"display_name" yaml:"display_name"`
	GrantedAt      time.Time `json:"granted_at" yaml:"granted_at"`
}

// AdminList represents a structured data type
type AdminList struct {
	Admins []AdminUser `json:"admins" yaml:"admins"`
}

// SetAdminRequest represents a structured data type
type SetAdminRequest struct {
	UserId  UserID `json:"user_id" yaml:"user_id"`
	Granted bool   `json:"granted" yaml:"granted"`
}

// FindUserRequest represents a structured data type
type FindUserRequest struct {
	Handle string `json:"handle" yaml:"handle"`
	Domain string `json:"domain" yaml:"domain"`
}

// UserRef represents a structured data type
type UserRef struct {
	UserId         UserID `json:"user_id" yaml:"user_id"`
	Handle         string `json:"handle" yaml:"handle"`
	LinkkeysDomain string `json:"linkkeys_domain" yaml:"linkkeys_domain"`
	DisplayName    string `json:"display_name" yaml:"display_name"`
	IsAdmin        bool   `json:"is_admin" yaml:"is_admin"`
}

// UserRefList represents a structured data type
type UserRefList struct {
	Users []UserRef `json:"users" yaml:"users"`
}

// SearchUsersRequest represents a structured data type
type SearchUsersRequest struct {
	Query string `json:"query" yaml:"query"`
	Page  *Page  `json:"page,omitempty" yaml:"page,omitempty"`
}

// InstanceSettings represents a structured data type
type InstanceSettings struct {
	PublishDefault              PublishSetting `json:"publish_default" yaml:"publish_default"`
	OrganizationOverrideAllowed bool           `json:"organization_override_allowed" yaml:"organization_override_allowed"`
	GatheringOverrideAllowed    bool           `json:"gathering_override_allowed" yaml:"gathering_override_allowed"`
	RetentionDays               uint64         `json:"retention_days" yaml:"retention_days"`
	PeerRateLimitPerMinute      uint64         `json:"peer_rate_limit_per_minute" yaml:"peer_rate_limit_per_minute"`
	OriginRateLimitPerMinute    uint64         `json:"origin_rate_limit_per_minute" yaml:"origin_rate_limit_per_minute"`
}

// UpdateInstanceSettingsRequest represents a structured data type
type UpdateInstanceSettingsRequest struct {
	PublishDefault              *PublishSetting `json:"publish_default,omitempty" yaml:"publish_default,omitempty"`
	OrganizationOverrideAllowed *bool           `json:"organization_override_allowed,omitempty" yaml:"organization_override_allowed,omitempty"`
	GatheringOverrideAllowed    *bool           `json:"gathering_override_allowed,omitempty" yaml:"gathering_override_allowed,omitempty"`
	RetentionDays               *uint64         `json:"retention_days,omitempty" yaml:"retention_days,omitempty"`
	PeerRateLimitPerMinute      *uint64         `json:"peer_rate_limit_per_minute,omitempty" yaml:"peer_rate_limit_per_minute,omitempty"`
	OriginRateLimitPerMinute    *uint64         `json:"origin_rate_limit_per_minute,omitempty" yaml:"origin_rate_limit_per_minute,omitempty"`
}

// PeerStatus is a type alias
type PeerStatus string

// Peer represents a structured data type
type Peer struct {
	Id                 string     `json:"id" yaml:"id"`
	Address            string     `json:"address" yaml:"address"`
	Handle             string     `json:"handle" yaml:"handle"`
	Domain             string     `json:"domain" yaml:"domain"`
	SubjectUserId      *string    `json:"subject_user_id,omitempty" yaml:"subject_user_id,omitempty"`
	SubjectDomain      *string    `json:"subject_domain,omitempty" yaml:"subject_domain,omitempty"`
	ApplicationId      *string    `json:"application_id,omitempty" yaml:"application_id,omitempty"`
	InstanceId         *string    `json:"instance_id,omitempty" yaml:"instance_id,omitempty"`
	BaseUrl            string     `json:"base_url" yaml:"base_url"`
	InboundStatus      PeerStatus `json:"inbound_status" yaml:"inbound_status"`
	OutboundStatus     PeerStatus `json:"outbound_status" yaml:"outbound_status"`
	Note               string     `json:"note" yaml:"note"`
	Suspended          bool       `json:"suspended" yaml:"suspended"`
	SuspendedAt        *time.Time `json:"suspended_at,omitempty" yaml:"suspended_at,omitempty"`
	FirstFailureAt     *time.Time `json:"first_failure_at,omitempty" yaml:"first_failure_at,omitempty"`
	LastFailureAt      *time.Time `json:"last_failure_at,omitempty" yaml:"last_failure_at,omitempty"`
	LastFailureReason  string     `json:"last_failure_reason" yaml:"last_failure_reason"`
	LastSuccessAt      *time.Time `json:"last_success_at,omitempty" yaml:"last_success_at,omitempty"`
	PendingDeliveries  uint64     `json:"pending_deliveries" yaml:"pending_deliveries"`
	RateLimitPerMinute *uint64    `json:"rate_limit_per_minute,omitempty" yaml:"rate_limit_per_minute,omitempty"`
	RateLimitedTotal   uint64     `json:"rate_limited_total" yaml:"rate_limited_total"`
	CreatedAt          time.Time  `json:"created_at" yaml:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at" yaml:"updated_at"`
}

// PeerList represents a structured data type
type PeerList struct {
	Peers []Peer `json:"peers" yaml:"peers"`
	Total uint64 `json:"total" yaml:"total"`
}

// ListPeersRequest represents a structured data type
type ListPeersRequest struct {
	Page *Page `json:"page,omitempty" yaml:"page,omitempty"`
}

// AddPeerRequest represents a structured data type
type AddPeerRequest struct {
	Address string `json:"address" yaml:"address"`
	BaseUrl string `json:"base_url" yaml:"base_url"`
	Note    string `json:"note" yaml:"note"`
}

// SetPeerStatusRequest represents a structured data type
type SetPeerStatusRequest struct {
	PeerId         string      `json:"peer_id" yaml:"peer_id"`
	InboundStatus  *PeerStatus `json:"inbound_status,omitempty" yaml:"inbound_status,omitempty"`
	OutboundStatus *PeerStatus `json:"outbound_status,omitempty" yaml:"outbound_status,omitempty"`
	SubjectUserId  *string     `json:"subject_user_id,omitempty" yaml:"subject_user_id,omitempty"`
	SubjectDomain  *string     `json:"subject_domain,omitempty" yaml:"subject_domain,omitempty"`
	ApplicationId  *string     `json:"application_id,omitempty" yaml:"application_id,omitempty"`
	InstanceId     *string     `json:"instance_id,omitempty" yaml:"instance_id,omitempty"`
}

// ResumePeerRequest represents a structured data type
type ResumePeerRequest struct {
	PeerId string `json:"peer_id" yaml:"peer_id"`
}

// SetPeerRateLimitRequest represents a structured data type
type SetPeerRateLimitRequest struct {
	PeerId             string  `json:"peer_id" yaml:"peer_id"`
	RateLimitPerMinute *uint64 `json:"rate_limit_per_minute,omitempty" yaml:"rate_limit_per_minute,omitempty"`
}

// RemovePeerRequest represents a structured data type
type RemovePeerRequest struct {
	PeerId string `json:"peer_id" yaml:"peer_id"`
}

// FederatedEvent represents a structured data type
type FederatedEvent struct {
	RemoteId         string    `json:"remote_id" yaml:"remote_id"`
	CanonicalUrl     string    `json:"canonical_url" yaml:"canonical_url"`
	Title            string    `json:"title" yaml:"title"`
	IsOnline         bool      `json:"is_online" yaml:"is_online"`
	IsInPerson       bool      `json:"is_in_person" yaml:"is_in_person"`
	Location         *Location `json:"location,omitempty" yaml:"location,omitempty"`
	StartsAt         time.Time `json:"starts_at" yaml:"starts_at"`
	EndsAt           time.Time `json:"ends_at" yaml:"ends_at"`
	Timezone         string    `json:"timezone" yaml:"timezone"`
	GatheringName    string    `json:"gathering_name" yaml:"gathering_name"`
	OrganizationName string    `json:"organization_name" yaml:"organization_name"`
	Deleted          bool      `json:"deleted" yaml:"deleted"`
}

// EventBatch represents a structured data type
type EventBatch struct {
	OriginDomain string           `json:"origin_domain" yaml:"origin_domain"`
	BatchId      string           `json:"batch_id" yaml:"batch_id"`
	SentAt       time.Time        `json:"sent_at" yaml:"sent_at"`
	Events       []FederatedEvent `json:"events" yaml:"events"`
}

// SignedDelivery represents a structured data type
type SignedDelivery struct {
	SenderAddress string `json:"sender_address" yaml:"sender_address"`
	Algorithm     string `json:"algorithm" yaml:"algorithm"`
	KeyId         string `json:"key_id" yaml:"key_id"`
	Signature     string `json:"signature" yaml:"signature"`
	Body          []byte `json:"body" yaml:"body"`
}

// DeliveryReceipt represents a structured data type
type DeliveryReceipt struct {
	Accepted    uint64  `json:"accepted" yaml:"accepted"`
	Rejected    uint64  `json:"rejected" yaml:"rejected"`
	Message     *string `json:"message,omitempty" yaml:"message,omitempty"`
	RateLimited uint64  `json:"rate_limited" yaml:"rate_limited"`
}

// PeeringBody represents a structured data type
type PeeringBody struct {
	BaseUrl     string    `json:"base_url" yaml:"base_url"`
	Note        string    `json:"note" yaml:"note"`
	RequestedAt time.Time `json:"requested_at" yaml:"requested_at"`
}

// SignedPeeringRequest represents a structured data type
type SignedPeeringRequest struct {
	SenderAddress string `json:"sender_address" yaml:"sender_address"`
	Algorithm     string `json:"algorithm" yaml:"algorithm"`
	KeyId         string `json:"key_id" yaml:"key_id"`
	SubjectUserId string `json:"subject_user_id" yaml:"subject_user_id"`
	SubjectDomain string `json:"subject_domain" yaml:"subject_domain"`
	ApplicationId string `json:"application_id" yaml:"application_id"`
	InstanceId    string `json:"instance_id" yaml:"instance_id"`
	Signature     string `json:"signature" yaml:"signature"`
	Body          []byte `json:"body" yaml:"body"`
}

// PeeringReceipt represents a structured data type
type PeeringReceipt struct {
	Status PeerStatus `json:"status" yaml:"status"`
}

// RemoteEvent represents a structured data type
type RemoteEvent struct {
	Id               string    `json:"id" yaml:"id"`
	PeerAddress      string    `json:"peer_address" yaml:"peer_address"`
	Origin           Origin    `json:"origin" yaml:"origin"`
	OriginDomain     string    `json:"origin_domain" yaml:"origin_domain"`
	RemoteId         string    `json:"remote_id" yaml:"remote_id"`
	CanonicalUrl     string    `json:"canonical_url" yaml:"canonical_url"`
	Title            string    `json:"title" yaml:"title"`
	IsOnline         bool      `json:"is_online" yaml:"is_online"`
	IsInPerson       bool      `json:"is_in_person" yaml:"is_in_person"`
	Location         *Location `json:"location,omitempty" yaml:"location,omitempty"`
	StartsAt         time.Time `json:"starts_at" yaml:"starts_at"`
	EndsAt           time.Time `json:"ends_at" yaml:"ends_at"`
	Timezone         string    `json:"timezone" yaml:"timezone"`
	GatheringName    string    `json:"gathering_name" yaml:"gathering_name"`
	OrganizationName string    `json:"organization_name" yaml:"organization_name"`
	ReceivedAt       time.Time `json:"received_at" yaml:"received_at"`
}

// RemoteEventList represents a structured data type
type RemoteEventList struct {
	Events []RemoteEvent `json:"events" yaml:"events"`
	Total  uint64        `json:"total" yaml:"total"`
}

// ListRemoteEventsRequest represents a structured data type
type ListRemoteEventsRequest struct {
	Query        *string    `json:"query,omitempty" yaml:"query,omitempty"`
	StartsAfter  *time.Time `json:"starts_after,omitempty" yaml:"starts_after,omitempty"`
	StartsBefore *time.Time `json:"starts_before,omitempty" yaml:"starts_before,omitempty"`
	Page         *Page      `json:"page,omitempty" yaml:"page,omitempty"`
}

// FederationIdentity represents a structured data type
type FederationIdentity struct {
	Address       string `json:"address" yaml:"address"`
	Enabled       bool   `json:"enabled" yaml:"enabled"`
	Algorithm     string `json:"algorithm" yaml:"algorithm"`
	SubjectUserId string `json:"subject_user_id" yaml:"subject_user_id"`
	SubjectDomain string `json:"subject_domain" yaml:"subject_domain"`
	ApplicationId string `json:"application_id" yaml:"application_id"`
	InstanceId    string `json:"instance_id" yaml:"instance_id"`
}

// OriginVolume represents a structured data type
type OriginVolume struct {
	PeerId                      string     `json:"peer_id" yaml:"peer_id"`
	PeerAddress                 string     `json:"peer_address" yaml:"peer_address"`
	OrganizationName            string     `json:"organization_name" yaml:"organization_name"`
	Held                        uint64     `json:"held" yaml:"held"`
	AcceptedTotal               uint64     `json:"accepted_total" yaml:"accepted_total"`
	AcceptedThisMinute          uint64     `json:"accepted_this_minute" yaml:"accepted_this_minute"`
	LastReceivedAt              *time.Time `json:"last_received_at,omitempty" yaml:"last_received_at,omitempty"`
	PeerRateLimitPerMinute      uint64     `json:"peer_rate_limit_per_minute" yaml:"peer_rate_limit_per_minute"`
	PeerRateLimitedTotal        uint64     `json:"peer_rate_limited_total" yaml:"peer_rate_limited_total"`
	PeerSuspended               bool       `json:"peer_suspended" yaml:"peer_suspended"`
	RateLimitPerMinute          *uint64    `json:"rate_limit_per_minute,omitempty" yaml:"rate_limit_per_minute,omitempty"`
	EffectiveRateLimitPerMinute uint64     `json:"effective_rate_limit_per_minute" yaml:"effective_rate_limit_per_minute"`
	RateLimitedTotal            uint64     `json:"rate_limited_total" yaml:"rate_limited_total"`
}

// SetOriginRateLimitRequest represents a structured data type
type SetOriginRateLimitRequest struct {
	PeerId             string  `json:"peer_id" yaml:"peer_id"`
	OrganizationName   string  `json:"organization_name" yaml:"organization_name"`
	RateLimitPerMinute *uint64 `json:"rate_limit_per_minute,omitempty" yaml:"rate_limit_per_minute,omitempty"`
}

// OriginVolumeList represents a structured data type
type OriginVolumeList struct {
	Origins []OriginVolume `json:"origins" yaml:"origins"`
	Total   uint64         `json:"total" yaml:"total"`
}

// ListOriginVolumeRequest represents a structured data type
type ListOriginVolumeRequest struct {
	PeerId *string `json:"peer_id,omitempty" yaml:"peer_id,omitempty"`
	Page   *Page   `json:"page,omitempty" yaml:"page,omitempty"`
}
