// Package csil contains generated validation functions.
//
// Code generated by csilgen; DO NOT EDIT.
package csil

import (
	"fmt"
	"regexp"
)

// ValidateBeginLoginRequest validates the BeginLoginRequest struct
func (v *BeginLoginRequest) Validate() error {
	if len(v.Domain) < 1 {
		return fmt.Errorf("field 'Domain' must have at least 1 elements")
	}
	if len(v.Domain) > 253 {
		return fmt.Errorf("field 'Domain' must have at most 253 elements")
	}
	return nil
}

// ValidateDevLoginRequest validates the DevLoginRequest struct
func (v *DevLoginRequest) Validate() error {
	if len(v.Handle) < 1 {
		return fmt.Errorf("field 'Handle' must have at least 1 elements")
	}
	if len(v.Handle) > 64 {
		return fmt.Errorf("field 'Handle' must have at most 64 elements")
	}
	matched, _ := regexp.MatchString(`^[a-z0-9]+(-[a-z0-9]+)*$`, v.Handle)
	if !matched {
		return fmt.Errorf("field 'Handle' must match pattern '^[a-z0-9]+(-[a-z0-9]+)*$'")
	}
	if len(v.Domain) < 1 {
		return fmt.Errorf("field 'Domain' must have at least 1 elements")
	}
	if len(v.Domain) > 253 {
		return fmt.Errorf("field 'Domain' must have at most 253 elements")
	}
	return nil
}

// ValidateGreeting validates the Greeting struct
func (v *Greeting) Validate() error {
	if len(v.Message) < 1 {
		return fmt.Errorf("field 'Message' must have at least 1 elements")
	}
	if len(v.Message) > 280 {
		return fmt.Errorf("field 'Message' must have at most 280 elements")
	}
	return nil
}

// ValidateCreateGreetingRequest validates the CreateGreetingRequest struct
func (v *CreateGreetingRequest) Validate() error {
	if len(v.Message) < 1 {
		return fmt.Errorf("field 'Message' must have at least 1 elements")
	}
	if len(v.Message) > 280 {
		return fmt.Errorf("field 'Message' must have at most 280 elements")
	}
	return nil
}

// ValidateOrganization validates the Organization struct
func (v *Organization) Validate() error {
	if len(v.Name) < 1 {
		return fmt.Errorf("field 'Name' must have at least 1 elements")
	}
	if len(v.Name) > 120 {
		return fmt.Errorf("field 'Name' must have at most 120 elements")
	}
	if len(v.Blurb) < 0 {
		return fmt.Errorf("field 'Blurb' must have at least 0 elements")
	}
	if len(v.Blurb) > 4000 {
		return fmt.Errorf("field 'Blurb' must have at most 4000 elements")
	}
	if len(v.Description) < 0 {
		return fmt.Errorf("field 'Description' must have at least 0 elements")
	}
	if len(v.Description) > 10000 {
		return fmt.Errorf("field 'Description' must have at most 10000 elements")
	}
	return nil
}

// ValidateCreateOrganizationRequest validates the CreateOrganizationRequest struct
func (v *CreateOrganizationRequest) Validate() error {
	if len(v.Name) < 1 {
		return fmt.Errorf("field 'Name' must have at least 1 elements")
	}
	if len(v.Name) > 120 {
		return fmt.Errorf("field 'Name' must have at most 120 elements")
	}
	if len(v.Blurb) < 0 {
		return fmt.Errorf("field 'Blurb' must have at least 0 elements")
	}
	if len(v.Blurb) > 4000 {
		return fmt.Errorf("field 'Blurb' must have at most 4000 elements")
	}
	if len(v.Description) < 0 {
		return fmt.Errorf("field 'Description' must have at least 0 elements")
	}
	if len(v.Description) > 10000 {
		return fmt.Errorf("field 'Description' must have at most 10000 elements")
	}
	return nil
}

// ValidateUpdateOrganizationRequest validates the UpdateOrganizationRequest struct
func (v *UpdateOrganizationRequest) Validate() error {
	if v.Name != nil {
		if len((*v.Name)) < 1 {
			return fmt.Errorf("field 'Name' must have at least 1 elements")
		}
	}
	if v.Name != nil {
		if len((*v.Name)) > 120 {
			return fmt.Errorf("field 'Name' must have at most 120 elements")
		}
	}
	if v.Blurb != nil {
		if len((*v.Blurb)) < 0 {
			return fmt.Errorf("field 'Blurb' must have at least 0 elements")
		}
	}
	if v.Blurb != nil {
		if len((*v.Blurb)) > 4000 {
			return fmt.Errorf("field 'Blurb' must have at most 4000 elements")
		}
	}
	if v.Description != nil {
		if len((*v.Description)) < 0 {
			return fmt.Errorf("field 'Description' must have at least 0 elements")
		}
	}
	if v.Description != nil {
		if len((*v.Description)) > 10000 {
			return fmt.Errorf("field 'Description' must have at most 10000 elements")
		}
	}
	return nil
}

// ValidateGathering validates the Gathering struct
func (v *Gathering) Validate() error {
	if len(v.Name) < 1 {
		return fmt.Errorf("field 'Name' must have at least 1 elements")
	}
	if len(v.Name) > 120 {
		return fmt.Errorf("field 'Name' must have at most 120 elements")
	}
	if len(v.Blurb) < 0 {
		return fmt.Errorf("field 'Blurb' must have at least 0 elements")
	}
	if len(v.Blurb) > 4000 {
		return fmt.Errorf("field 'Blurb' must have at most 4000 elements")
	}
	if len(v.Description) < 0 {
		return fmt.Errorf("field 'Description' must have at least 0 elements")
	}
	if len(v.Description) > 10000 {
		return fmt.Errorf("field 'Description' must have at most 10000 elements")
	}
	return nil
}

// ValidateCreateGatheringRequest validates the CreateGatheringRequest struct
func (v *CreateGatheringRequest) Validate() error {
	if len(v.Name) < 1 {
		return fmt.Errorf("field 'Name' must have at least 1 elements")
	}
	if len(v.Name) > 120 {
		return fmt.Errorf("field 'Name' must have at most 120 elements")
	}
	if len(v.Blurb) < 0 {
		return fmt.Errorf("field 'Blurb' must have at least 0 elements")
	}
	if len(v.Blurb) > 4000 {
		return fmt.Errorf("field 'Blurb' must have at most 4000 elements")
	}
	if len(v.Description) < 0 {
		return fmt.Errorf("field 'Description' must have at least 0 elements")
	}
	if len(v.Description) > 10000 {
		return fmt.Errorf("field 'Description' must have at most 10000 elements")
	}
	return nil
}

// ValidateUpdateGatheringRequest validates the UpdateGatheringRequest struct
func (v *UpdateGatheringRequest) Validate() error {
	if v.Name != nil {
		if len((*v.Name)) < 1 {
			return fmt.Errorf("field 'Name' must have at least 1 elements")
		}
	}
	if v.Name != nil {
		if len((*v.Name)) > 120 {
			return fmt.Errorf("field 'Name' must have at most 120 elements")
		}
	}
	if v.Blurb != nil {
		if len((*v.Blurb)) < 0 {
			return fmt.Errorf("field 'Blurb' must have at least 0 elements")
		}
	}
	if v.Blurb != nil {
		if len((*v.Blurb)) > 4000 {
			return fmt.Errorf("field 'Blurb' must have at most 4000 elements")
		}
	}
	if v.Description != nil {
		if len((*v.Description)) < 0 {
			return fmt.Errorf("field 'Description' must have at least 0 elements")
		}
	}
	if v.Description != nil {
		if len((*v.Description)) > 10000 {
			return fmt.Errorf("field 'Description' must have at most 10000 elements")
		}
	}
	return nil
}

// ValidateLocation validates the Location struct
func (v *Location) Validate() error {
	if len(v.Name) < 0 {
		return fmt.Errorf("field 'Name' must have at least 0 elements")
	}
	if len(v.Name) > 200 {
		return fmt.Errorf("field 'Name' must have at most 200 elements")
	}
	if len(v.Address) < 0 {
		return fmt.Errorf("field 'Address' must have at least 0 elements")
	}
	if len(v.Address) > 300 {
		return fmt.Errorf("field 'Address' must have at most 300 elements")
	}
	if len(v.Locality) < 0 {
		return fmt.Errorf("field 'Locality' must have at least 0 elements")
	}
	if len(v.Locality) > 120 {
		return fmt.Errorf("field 'Locality' must have at most 120 elements")
	}
	if len(v.Region) < 0 {
		return fmt.Errorf("field 'Region' must have at least 0 elements")
	}
	if len(v.Region) > 120 {
		return fmt.Errorf("field 'Region' must have at most 120 elements")
	}
	if len(v.PostalCode) < 0 {
		return fmt.Errorf("field 'PostalCode' must have at least 0 elements")
	}
	if len(v.PostalCode) > 32 {
		return fmt.Errorf("field 'PostalCode' must have at most 32 elements")
	}
	if len(v.Country) < 0 {
		return fmt.Errorf("field 'Country' must have at least 0 elements")
	}
	if len(v.Country) > 2 {
		return fmt.Errorf("field 'Country' must have at most 2 elements")
	}
	return nil
}

// ValidateEvent validates the Event struct
func (v *Event) Validate() error {
	if len(v.Title) < 1 {
		return fmt.Errorf("field 'Title' must have at least 1 elements")
	}
	if len(v.Title) > 200 {
		return fmt.Errorf("field 'Title' must have at most 200 elements")
	}
	if v.Description != nil {
		if len((*v.Description)) < 0 {
			return fmt.Errorf("field 'Description' must have at least 0 elements")
		}
	}
	if v.Description != nil {
		if len((*v.Description)) > 10000 {
			return fmt.Errorf("field 'Description' must have at most 10000 elements")
		}
	}
	if v.OnlineUrl != nil {
		if len((*v.OnlineUrl)) < 0 {
			return fmt.Errorf("field 'OnlineUrl' must have at least 0 elements")
		}
	}
	if v.OnlineUrl != nil {
		if len((*v.OnlineUrl)) > 2000 {
			return fmt.Errorf("field 'OnlineUrl' must have at most 2000 elements")
		}
	}
	if len(v.Timezone) < 1 {
		return fmt.Errorf("field 'Timezone' must have at least 1 elements")
	}
	if len(v.Timezone) > 64 {
		return fmt.Errorf("field 'Timezone' must have at most 64 elements")
	}
	return nil
}

// ValidateEventSeries validates the EventSeries struct
func (v *EventSeries) Validate() error {
	if len(v.Title) < 1 {
		return fmt.Errorf("field 'Title' must have at least 1 elements")
	}
	if len(v.Title) > 200 {
		return fmt.Errorf("field 'Title' must have at most 200 elements")
	}
	if len(v.Description) < 0 {
		return fmt.Errorf("field 'Description' must have at least 0 elements")
	}
	if len(v.Description) > 10000 {
		return fmt.Errorf("field 'Description' must have at most 10000 elements")
	}
	if v.OnlineUrl != nil {
		if len((*v.OnlineUrl)) < 0 {
			return fmt.Errorf("field 'OnlineUrl' must have at least 0 elements")
		}
	}
	if v.OnlineUrl != nil {
		if len((*v.OnlineUrl)) > 2000 {
			return fmt.Errorf("field 'OnlineUrl' must have at most 2000 elements")
		}
	}
	if len(v.StartTime) < 5 {
		return fmt.Errorf("field 'StartTime' must have at least 5 elements")
	}
	if len(v.StartTime) > 5 {
		return fmt.Errorf("field 'StartTime' must have at most 5 elements")
	}
	matched, _ := regexp.MatchString(`^([01][0-9]|2[0-3]):[0-5][0-9]$`, v.StartTime)
	if !matched {
		return fmt.Errorf("field 'StartTime' must match pattern '^([01][0-9]|2[0-3]):[0-5][0-9]$'")
	}
	if len(v.Timezone) < 1 {
		return fmt.Errorf("field 'Timezone' must have at least 1 elements")
	}
	if len(v.Timezone) > 64 {
		return fmt.Errorf("field 'Timezone' must have at most 64 elements")
	}
	return nil
}

// ValidateCreateEventRequest validates the CreateEventRequest struct
func (v *CreateEventRequest) Validate() error {
	if len(v.Title) < 1 {
		return fmt.Errorf("field 'Title' must have at least 1 elements")
	}
	if len(v.Title) > 200 {
		return fmt.Errorf("field 'Title' must have at most 200 elements")
	}
	if len(v.Description) < 0 {
		return fmt.Errorf("field 'Description' must have at least 0 elements")
	}
	if len(v.Description) > 10000 {
		return fmt.Errorf("field 'Description' must have at most 10000 elements")
	}
	if v.OnlineUrl != nil {
		if len((*v.OnlineUrl)) < 0 {
			return fmt.Errorf("field 'OnlineUrl' must have at least 0 elements")
		}
	}
	if v.OnlineUrl != nil {
		if len((*v.OnlineUrl)) > 2000 {
			return fmt.Errorf("field 'OnlineUrl' must have at most 2000 elements")
		}
	}
	if len(v.Timezone) < 1 {
		return fmt.Errorf("field 'Timezone' must have at least 1 elements")
	}
	if len(v.Timezone) > 64 {
		return fmt.Errorf("field 'Timezone' must have at most 64 elements")
	}
	return nil
}

// ValidateUpdateEventRequest validates the UpdateEventRequest struct
func (v *UpdateEventRequest) Validate() error {
	if v.Title != nil {
		if len((*v.Title)) < 1 {
			return fmt.Errorf("field 'Title' must have at least 1 elements")
		}
	}
	if v.Title != nil {
		if len((*v.Title)) > 200 {
			return fmt.Errorf("field 'Title' must have at most 200 elements")
		}
	}
	if v.Description != nil {
		if len((*v.Description)) < 0 {
			return fmt.Errorf("field 'Description' must have at least 0 elements")
		}
	}
	if v.Description != nil {
		if len((*v.Description)) > 10000 {
			return fmt.Errorf("field 'Description' must have at most 10000 elements")
		}
	}
	if v.OnlineUrl != nil {
		if len((*v.OnlineUrl)) < 0 {
			return fmt.Errorf("field 'OnlineUrl' must have at least 0 elements")
		}
	}
	if v.OnlineUrl != nil {
		if len((*v.OnlineUrl)) > 2000 {
			return fmt.Errorf("field 'OnlineUrl' must have at most 2000 elements")
		}
	}
	if v.Timezone != nil {
		if len((*v.Timezone)) < 1 {
			return fmt.Errorf("field 'Timezone' must have at least 1 elements")
		}
	}
	if v.Timezone != nil {
		if len((*v.Timezone)) > 64 {
			return fmt.Errorf("field 'Timezone' must have at most 64 elements")
		}
	}
	return nil
}

// ValidateCreateEventSeriesRequest validates the CreateEventSeriesRequest struct
func (v *CreateEventSeriesRequest) Validate() error {
	if len(v.Title) < 1 {
		return fmt.Errorf("field 'Title' must have at least 1 elements")
	}
	if len(v.Title) > 200 {
		return fmt.Errorf("field 'Title' must have at most 200 elements")
	}
	if len(v.Description) < 0 {
		return fmt.Errorf("field 'Description' must have at least 0 elements")
	}
	if len(v.Description) > 10000 {
		return fmt.Errorf("field 'Description' must have at most 10000 elements")
	}
	if v.OnlineUrl != nil {
		if len((*v.OnlineUrl)) < 0 {
			return fmt.Errorf("field 'OnlineUrl' must have at least 0 elements")
		}
	}
	if v.OnlineUrl != nil {
		if len((*v.OnlineUrl)) > 2000 {
			return fmt.Errorf("field 'OnlineUrl' must have at most 2000 elements")
		}
	}
	if len(v.StartTime) < 5 {
		return fmt.Errorf("field 'StartTime' must have at least 5 elements")
	}
	if len(v.StartTime) > 5 {
		return fmt.Errorf("field 'StartTime' must have at most 5 elements")
	}
	matched, _ := regexp.MatchString(`^([01][0-9]|2[0-3]):[0-5][0-9]$`, v.StartTime)
	if !matched {
		return fmt.Errorf("field 'StartTime' must match pattern '^([01][0-9]|2[0-3]):[0-5][0-9]$'")
	}
	if len(v.Timezone) < 1 {
		return fmt.Errorf("field 'Timezone' must have at least 1 elements")
	}
	if len(v.Timezone) > 64 {
		return fmt.Errorf("field 'Timezone' must have at most 64 elements")
	}
	return nil
}

// ValidateUpdateEventSeriesRequest validates the UpdateEventSeriesRequest struct
func (v *UpdateEventSeriesRequest) Validate() error {
	if v.Title != nil {
		if len((*v.Title)) < 1 {
			return fmt.Errorf("field 'Title' must have at least 1 elements")
		}
	}
	if v.Title != nil {
		if len((*v.Title)) > 200 {
			return fmt.Errorf("field 'Title' must have at most 200 elements")
		}
	}
	if v.Description != nil {
		if len((*v.Description)) < 0 {
			return fmt.Errorf("field 'Description' must have at least 0 elements")
		}
	}
	if v.Description != nil {
		if len((*v.Description)) > 10000 {
			return fmt.Errorf("field 'Description' must have at most 10000 elements")
		}
	}
	if v.OnlineUrl != nil {
		if len((*v.OnlineUrl)) < 0 {
			return fmt.Errorf("field 'OnlineUrl' must have at least 0 elements")
		}
	}
	if v.OnlineUrl != nil {
		if len((*v.OnlineUrl)) > 2000 {
			return fmt.Errorf("field 'OnlineUrl' must have at most 2000 elements")
		}
	}
	if v.StartTime != nil {
		if len((*v.StartTime)) < 5 {
			return fmt.Errorf("field 'StartTime' must have at least 5 elements")
		}
	}
	if v.StartTime != nil {
		if len((*v.StartTime)) > 5 {
			return fmt.Errorf("field 'StartTime' must have at most 5 elements")
		}
	}
	if v.StartTime != nil {
		matched, _ := regexp.MatchString(`^([01][0-9]|2[0-3]):[0-5][0-9]$`, (*v.StartTime))
		if !matched {
			return fmt.Errorf("field 'StartTime' must match pattern '^([01][0-9]|2[0-3]):[0-5][0-9]$'")
		}
	}
	if v.Timezone != nil {
		if len((*v.Timezone)) < 1 {
			return fmt.Errorf("field 'Timezone' must have at least 1 elements")
		}
	}
	if v.Timezone != nil {
		if len((*v.Timezone)) > 64 {
			return fmt.Errorf("field 'Timezone' must have at most 64 elements")
		}
	}
	return nil
}

// ValidateLocationFilter validates the LocationFilter struct
func (v *LocationFilter) Validate() error {
	if v.Locality != nil {
		if len((*v.Locality)) < 0 {
			return fmt.Errorf("field 'Locality' must have at least 0 elements")
		}
	}
	if v.Locality != nil {
		if len((*v.Locality)) > 120 {
			return fmt.Errorf("field 'Locality' must have at most 120 elements")
		}
	}
	if v.Region != nil {
		if len((*v.Region)) < 0 {
			return fmt.Errorf("field 'Region' must have at least 0 elements")
		}
	}
	if v.Region != nil {
		if len((*v.Region)) > 120 {
			return fmt.Errorf("field 'Region' must have at most 120 elements")
		}
	}
	if v.Country != nil {
		if len((*v.Country)) < 0 {
			return fmt.Errorf("field 'Country' must have at least 0 elements")
		}
	}
	if v.Country != nil {
		if len((*v.Country)) > 2 {
			return fmt.Errorf("field 'Country' must have at most 2 elements")
		}
	}
	return nil
}

// ValidateSearchRequest validates the SearchRequest struct
func (v *SearchRequest) Validate() error {
	if v.Query != nil {
		if len((*v.Query)) < 0 {
			return fmt.Errorf("field 'Query' must have at least 0 elements")
		}
	}
	if v.Query != nil {
		if len((*v.Query)) > 200 {
			return fmt.Errorf("field 'Query' must have at most 200 elements")
		}
	}
	return nil
}

// ValidateFindUserRequest validates the FindUserRequest struct
func (v *FindUserRequest) Validate() error {
	if len(v.Handle) < 1 {
		return fmt.Errorf("field 'Handle' must have at least 1 elements")
	}
	if len(v.Handle) > 64 {
		return fmt.Errorf("field 'Handle' must have at most 64 elements")
	}
	if len(v.Domain) < 1 {
		return fmt.Errorf("field 'Domain' must have at least 1 elements")
	}
	if len(v.Domain) > 253 {
		return fmt.Errorf("field 'Domain' must have at most 253 elements")
	}
	return nil
}

// ValidateSearchUsersRequest validates the SearchUsersRequest struct
func (v *SearchUsersRequest) Validate() error {
	if len(v.Query) < 1 {
		return fmt.Errorf("field 'Query' must have at least 1 elements")
	}
	if len(v.Query) > 64 {
		return fmt.Errorf("field 'Query' must have at most 64 elements")
	}
	return nil
}

// ValidatePeer validates the Peer struct
func (v *Peer) Validate() error {
	if len(v.BaseUrl) < 0 {
		return fmt.Errorf("field 'BaseUrl' must have at least 0 elements")
	}
	if len(v.BaseUrl) > 2000 {
		return fmt.Errorf("field 'BaseUrl' must have at most 2000 elements")
	}
	if len(v.Note) < 0 {
		return fmt.Errorf("field 'Note' must have at least 0 elements")
	}
	if len(v.Note) > 1000 {
		return fmt.Errorf("field 'Note' must have at most 1000 elements")
	}
	return nil
}

// ValidateAddPeerRequest validates the AddPeerRequest struct
func (v *AddPeerRequest) Validate() error {
	if len(v.Address) < 3 {
		return fmt.Errorf("field 'Address' must have at least 3 elements")
	}
	if len(v.Address) > 317 {
		return fmt.Errorf("field 'Address' must have at most 317 elements")
	}
	if len(v.BaseUrl) < 1 {
		return fmt.Errorf("field 'BaseUrl' must have at least 1 elements")
	}
	if len(v.BaseUrl) > 2000 {
		return fmt.Errorf("field 'BaseUrl' must have at most 2000 elements")
	}
	if len(v.Note) < 0 {
		return fmt.Errorf("field 'Note' must have at least 0 elements")
	}
	if len(v.Note) > 1000 {
		return fmt.Errorf("field 'Note' must have at most 1000 elements")
	}
	return nil
}

// ValidateFederatedEvent validates the FederatedEvent struct
func (v *FederatedEvent) Validate() error {
	if len(v.CanonicalUrl) < 1 {
		return fmt.Errorf("field 'CanonicalUrl' must have at least 1 elements")
	}
	if len(v.CanonicalUrl) > 2000 {
		return fmt.Errorf("field 'CanonicalUrl' must have at most 2000 elements")
	}
	if len(v.Title) < 1 {
		return fmt.Errorf("field 'Title' must have at least 1 elements")
	}
	if len(v.Title) > 200 {
		return fmt.Errorf("field 'Title' must have at most 200 elements")
	}
	if len(v.Timezone) < 1 {
		return fmt.Errorf("field 'Timezone' must have at least 1 elements")
	}
	if len(v.Timezone) > 64 {
		return fmt.Errorf("field 'Timezone' must have at most 64 elements")
	}
	if len(v.GatheringName) < 0 {
		return fmt.Errorf("field 'GatheringName' must have at least 0 elements")
	}
	if len(v.GatheringName) > 120 {
		return fmt.Errorf("field 'GatheringName' must have at most 120 elements")
	}
	if len(v.OrganizationName) < 0 {
		return fmt.Errorf("field 'OrganizationName' must have at least 0 elements")
	}
	if len(v.OrganizationName) > 120 {
		return fmt.Errorf("field 'OrganizationName' must have at most 120 elements")
	}
	return nil
}

// ValidateEventBatch validates the EventBatch struct
func (v *EventBatch) Validate() error {
	if len(v.BatchId) < 1 {
		return fmt.Errorf("field 'BatchId' must have at least 1 elements")
	}
	if len(v.BatchId) > 64 {
		return fmt.Errorf("field 'BatchId' must have at most 64 elements")
	}
	return nil
}

// ValidateSignedDelivery validates the SignedDelivery struct
func (v *SignedDelivery) Validate() error {
	if len(v.SenderAddress) < 3 {
		return fmt.Errorf("field 'SenderAddress' must have at least 3 elements")
	}
	if len(v.SenderAddress) > 317 {
		return fmt.Errorf("field 'SenderAddress' must have at most 317 elements")
	}
	if len(v.Algorithm) < 1 {
		return fmt.Errorf("field 'Algorithm' must have at least 1 elements")
	}
	if len(v.Algorithm) > 64 {
		return fmt.Errorf("field 'Algorithm' must have at most 64 elements")
	}
	if len(v.KeyId) < 1 {
		return fmt.Errorf("field 'KeyId' must have at least 1 elements")
	}
	if len(v.KeyId) > 128 {
		return fmt.Errorf("field 'KeyId' must have at most 128 elements")
	}
	if len(v.Signature) < 1 {
		return fmt.Errorf("field 'Signature' must have at least 1 elements")
	}
	if len(v.Signature) > 4000 {
		return fmt.Errorf("field 'Signature' must have at most 4000 elements")
	}
	return nil
}

// ValidatePeeringBody validates the PeeringBody struct
func (v *PeeringBody) Validate() error {
	if len(v.BaseUrl) < 1 {
		return fmt.Errorf("field 'BaseUrl' must have at least 1 elements")
	}
	if len(v.BaseUrl) > 2000 {
		return fmt.Errorf("field 'BaseUrl' must have at most 2000 elements")
	}
	if len(v.Note) < 0 {
		return fmt.Errorf("field 'Note' must have at least 0 elements")
	}
	if len(v.Note) > 1000 {
		return fmt.Errorf("field 'Note' must have at most 1000 elements")
	}
	return nil
}

// ValidateSignedPeeringRequest validates the SignedPeeringRequest struct
func (v *SignedPeeringRequest) Validate() error {
	if len(v.SenderAddress) < 3 {
		return fmt.Errorf("field 'SenderAddress' must have at least 3 elements")
	}
	if len(v.SenderAddress) > 317 {
		return fmt.Errorf("field 'SenderAddress' must have at most 317 elements")
	}
	if len(v.Algorithm) < 1 {
		return fmt.Errorf("field 'Algorithm' must have at least 1 elements")
	}
	if len(v.Algorithm) > 64 {
		return fmt.Errorf("field 'Algorithm' must have at most 64 elements")
	}
	if len(v.KeyId) < 1 {
		return fmt.Errorf("field 'KeyId' must have at least 1 elements")
	}
	if len(v.KeyId) > 128 {
		return fmt.Errorf("field 'KeyId' must have at most 128 elements")
	}
	if len(v.SubjectUserId) < 1 {
		return fmt.Errorf("field 'SubjectUserId' must have at least 1 elements")
	}
	if len(v.SubjectUserId) > 128 {
		return fmt.Errorf("field 'SubjectUserId' must have at most 128 elements")
	}
	if len(v.SubjectDomain) < 1 {
		return fmt.Errorf("field 'SubjectDomain' must have at least 1 elements")
	}
	if len(v.SubjectDomain) > 253 {
		return fmt.Errorf("field 'SubjectDomain' must have at most 253 elements")
	}
	if len(v.ApplicationId) < 1 {
		return fmt.Errorf("field 'ApplicationId' must have at least 1 elements")
	}
	if len(v.ApplicationId) > 128 {
		return fmt.Errorf("field 'ApplicationId' must have at most 128 elements")
	}
	if len(v.InstanceId) < 1 {
		return fmt.Errorf("field 'InstanceId' must have at least 1 elements")
	}
	if len(v.InstanceId) > 128 {
		return fmt.Errorf("field 'InstanceId' must have at most 128 elements")
	}
	if len(v.Signature) < 1 {
		return fmt.Errorf("field 'Signature' must have at least 1 elements")
	}
	if len(v.Signature) > 4000 {
		return fmt.Errorf("field 'Signature' must have at most 4000 elements")
	}
	return nil
}

// ValidateListRemoteEventsRequest validates the ListRemoteEventsRequest struct
func (v *ListRemoteEventsRequest) Validate() error {
	if v.Query != nil {
		if len((*v.Query)) < 0 {
			return fmt.Errorf("field 'Query' must have at least 0 elements")
		}
	}
	if v.Query != nil {
		if len((*v.Query)) > 200 {
			return fmt.Errorf("field 'Query' must have at most 200 elements")
		}
	}
	return nil
}
